// packages/client/src/pages/JobDetail.svelte
<script lang="ts">
  import { onDestroy } from "svelte";
  import { navigate } from "../router";
  import { requestBack } from "../lib/nav-back";
  import { api, type Job } from "../lib/api";
  import { errorMessage } from "../lib/utils";
  import { shareLink } from "../lib/share";
  import { feed } from "../lib/feed-store.svelte";
  import { sessionAccess } from "../lib/session-access";
  import { markViewed } from "../lib/viewed";
  import { feedback } from "../lib/feedback.svelte";
  import { applicationIntent } from "../lib/application-intent.svelte";
  import { jobOriginalTimingLabel, jobTimingLabel } from "../lib/job-timing";
  import { presentPending } from "../lib/task-presentation.svelte";
  import { isIosApp } from "../lib/platform";
  import { roleLabel } from "../../../../shared/search-profile";
  import {
    extractPlainTextFromHtml,
    extractSalaryFromHtml,
    normalizeSalaryText,
    sanitizeJobDescriptionHtml,
  } from "../lib/job-content";
  import { DropdownMenu } from "bits-ui";
  import CompanyLogo from "../components/CompanyLogo.svelte";
  import Modal from "../components/Modal.svelte";
  import ScreenNav from "../components/ScreenNav.svelte";
  import BookmarkSimple from "phosphor-svelte/lib/BookmarkSimple";
  import MapPin from "phosphor-svelte/lib/MapPin";
  import Money from "phosphor-svelte/lib/Money";
  import ClockCounterClockwise from "phosphor-svelte/lib/ClockCounterClockwise";
  import ArrowSquareOut from "phosphor-svelte/lib/ArrowSquareOut";
  import Export from "phosphor-svelte/lib/Export";
  import DotsThree from "phosphor-svelte/lib/DotsThree";
  import CheckCircle from "phosphor-svelte/lib/CheckCircle";
  import X from "phosphor-svelte/lib/X";
  import Trash from "phosphor-svelte/lib/Trash";
  import MagicWand from "phosphor-svelte/lib/MagicWand";
  import EyeSlash from "phosphor-svelte/lib/EyeSlash";
  import Flag from "phosphor-svelte/lib/Flag";
  import Spinner from "../components/Spinner.svelte";

  let { jobId = null }: { jobId?: string | null } = $props();

  let job = $state<Job | null>(null);
  let loading: boolean = $state(true);
  let error: string | null = $state(null);
  let dismissing: boolean = $state(false);
  let saved: boolean = $state(false);
  let applied: boolean = $state(false);
  let applying: boolean = $state(false);
  let applyingPending: boolean = $state(false);
  let openingApplication: boolean = $state(false);
  let showBlockConfirm: boolean = $state(false);
  let showMore: boolean = $state(false);
  let blocking: boolean = $state(false);
  let descriptionPending: boolean = $state(false);
  let hidingCompany: boolean = $state(false);
  let showReport: boolean = $state(false);
  let reportType: string = $state("incorrect_details");
  let reportNotes: string = $state("");
  let reporting: boolean = $state(false);
  let openedJobId: string | null = null;
  let descriptionRefreshTimer: number | null = null;
  let descriptionRefreshAttempts = 0;

  const MAX_DESCRIPTION_REFRESH_ATTEMPTS = 5;
  const nativeIos = isIosApp();

  function clearDescriptionRefreshTimer() {
    if (descriptionRefreshTimer !== null) {
      window.clearTimeout(descriptionRefreshTimer);
      descriptionRefreshTimer = null;
    }
  }

  function removeFromFeedStore(id: string) {
    feed.jobs = feed.jobs.filter((item) => item.id !== id);
  }

  function restoreToFeedStore(nextJob: Job) {
    if (!feed.jobs.some((item) => item.id === nextJob.id)) {
      feed.jobs = [nextJob, ...feed.jobs];
    }
  }

  function syncJobState(nextJob: Job) {
    job = nextJob;
    saved = Boolean(nextJob?.saved);
    applied = Boolean(nextJob?.applied);
    descriptionPending = Boolean(nextJob?.content_pending && !nextJob?.description);
  }

  async function loadJobDetail(silent = false) {
    if (!jobId) return;
    if (!silent) {
      loading = true;
      error = null;
    }

    try {
      const nextJob = await api.jobs.get(jobId);
      syncJobState(nextJob);
      if (openedJobId !== jobId) {
        openedJobId = jobId;
        markViewed(jobId);
        void api.interactions.event({
          event_name: "job_opened",
          entity_type: "job",
          entity_id: jobId,
          properties: {},
        }).catch(() => undefined);
      }

      if (descriptionPending && descriptionRefreshAttempts < MAX_DESCRIPTION_REFRESH_ATTEMPTS) {
        clearDescriptionRefreshTimer();
        descriptionRefreshTimer = window.setTimeout(async () => {
          descriptionRefreshAttempts += 1;
          await loadJobDetail(true);
        }, nextJob.content_refresh_after_ms ?? 1500);
      } else if (descriptionPending) {
        descriptionPending = false;
        clearDescriptionRefreshTimer();
      } else if (!descriptionPending) {
        clearDescriptionRefreshTimer();
      }
    } catch (e) {
      if (!silent || !job) {
        error = errorMessage(e);
      }
    } finally {
      loading = false;
    }
  }

  $effect(() => {
    if (!jobId) return;
    applied = false;
    descriptionRefreshAttempts = 0;
    clearDescriptionRefreshTimer();
    void loadJobDetail();

    return () => {
      clearDescriptionRefreshTimer();
    };
  });

  onDestroy(() => {
    clearDescriptionRefreshTimer();
  });

  async function markApplied() {
    if (!jobId || !job || applying || (!nativeIos && applied)) return;
    applying = true;
    try {
      if (nativeIos && applied) {
        const restored = await presentPending(
          () => api.jobs.unmarkApplied(jobId),
          (pending) => { applyingPending = pending; },
        );
        applied = false;
        job = restored;
        restoreToFeedStore(restored);
        feedback.success("Removed from applied jobs");
        return;
      }
      await presentPending(
        () => api.jobs.markApplied(jobId),
        (pending) => { applyingPending = pending; },
      );
      applied = true;
      removeFromFeedStore(jobId);
      feedback.success("Added to applied jobs");
    } catch (e) {
      feedback.error(errorMessage(e, "Could not mark this job as applied."));
    } finally {
      applying = false;
      applyingPending = false;
    }
  }

  async function openApplication() {
    if (!job?.url || openingApplication) return;
    openingApplication = true;
    void api.interactions.event({
      event_name: "apply_clicked",
      entity_type: "job",
      entity_id: jobId ?? undefined,
      properties: {},
    }).catch(() => undefined);
    try {
      await applicationIntent.open(job);
    } catch (e) {
      feedback.error(errorMessage(e, "Could not open the application page."));
    } finally {
      openingApplication = false;
    }
  }

  async function handleDismiss() {
    if (!jobId || !job) return;
    const dismissedJob = job;
    dismissing = true;
    try {
      await api.jobs.dismiss(jobId);
      removeFromFeedStore(jobId);
      navigate("/");
      if (nativeIos) {
        feedback.show({
          message: "Job hidden from your feed",
          action: {
            label: "Undo",
            run: async () => {
              const restored = await api.jobs.undismiss(dismissedJob.id);
              restoreToFeedStore(restored);
            },
          },
        });
      }
    } catch (e) {
      feedback.error(errorMessage(e, "Could not dismiss this job."));
      dismissing = false;
    }
  }

  function shareJob() {
    if (!job) return;
    void shareLink({
      title: `${job.title} · ${job.company_name}`,
      text: `${job.title} at ${job.company_name}`,
      url: job.url || window.location.href,
    });
  }

  async function toggleSave() {
    if (!jobId) return;
    const newVal = !saved;
    saved = newVal;
    try {
      if (newVal) {
        await api.savedJobs.save(jobId);
      } else {
        await api.savedJobs.unsave(jobId);
      }
    } catch (e) {
      saved = !newVal;
      feedback.error(errorMessage(e, "Could not update your saved jobs."));
    }
  }

  async function handleBlock() {
    if (!jobId || blocking) return;
    blocking = true;
    try {
      await api.jobs.block(jobId);
      removeFromFeedStore(jobId);
      navigate("/");
    } catch (e) {
      feedback.error(errorMessage(e, "Could not block this job."));
      blocking = false;
    }
  }

  async function hideCompany() {
    if (!job?.company_id || hidingCompany) return;
    const companyId = job.company_id;
    const previousJobs = [...feed.jobs];
    hidingCompany = true;
    try {
      await api.companies.block(companyId);
      feed.jobs = feed.jobs.filter((item) => item.company_id !== job?.company_id);
      navigate("/");
      if (nativeIos) {
        feedback.show({
          message: `${job.company_name} hidden`,
          action: {
            label: "Undo",
            run: async () => {
              await api.companies.restore(companyId);
              feed.jobs = previousJobs;
            },
          },
        });
      }
    } catch (e) {
      feedback.error(errorMessage(e, "Could not hide this company."));
      hidingCompany = false;
    }
  }

  async function submitReport() {
    if (!jobId || reporting) return;
    reporting = true;
    try {
      await api.interactions.report({
        job_id: jobId,
        report_type: reportType,
        notes: reportNotes,
      });
      showReport = false;
      reportNotes = "";
      feedback.success("Report sent. Thanks for helping keep listings accurate.");
    } catch (e) {
      feedback.error(errorMessage(e, "Could not send that report."));
    } finally {
      reporting = false;
    }
  }

  let extractedSalary = $derived(job?.description ? extractSalaryFromHtml(job.description) : null);
  let displaySalary = $derived(normalizeSalaryText(
    job?.salary?.trim() ? job.salary : extractedSalary
  ));
  let originalTiming = $derived(job ? jobOriginalTimingLabel(job) : null);
  let quickFacts = $derived.by(() => {
    if (!job) return [];
    const details: string[] = [];
    if (nativeIos) {
      if (job.sponsorship_available === true) details.push("Sponsorship available");
      if (!displaySalary) details.push("Salary not listed");
      return details;
    }
    if (job.match_fact) details.push(job.match_fact);
    const specialty = job.specialties?.[0];
    if (specialty) details.push(`${roleLabel(specialty)} role`);
    if (job.sponsorship_available === true) details.push("Sponsorship available");
    if (!displaySalary) details.push("Salary not listed");
    if (job.evergreen) details.push("Evergreen listing");
    if (!job.posted_at) details.push("Post date unavailable");
    return [...new Set(details)].slice(0, 4);
  });
  let sanitizedDescription = $derived(job?.description ? sanitizeJobDescriptionHtml(job.description, {
    title: job.title,
    companyName: job.company_name,
  }) : "");
  let plainDescription = $derived.by(() => {
    return extractPlainTextFromHtml(job?.description);
  });

</script>

<div class="page pushed-screen">
  <ScreenNav
    title={nativeIos ? job?.title ?? "" : ""}
    collapsible={Boolean(job)}
    backLabel="Back to jobs"
    onBack={() => { if (!requestBack()) navigate("/"); }}
  >
    {#snippet trailing()}
      <div class="job-header-actions">
      <button class="icon-btn" aria-label="Share job" onclick={shareJob}>
        <Export size={19} color={nativeIos ? "var(--color-ink-2)" : "var(--color-ink-3)"} />
      </button>
      <button
        class="icon-btn"
        aria-label={saved ? "Remove from saved jobs" : "Save job"}
        aria-pressed={saved}
        onclick={toggleSave}
      >
        <span class="state-icon" aria-hidden="true">
          <span class:visible={!saved}><BookmarkSimple size={20} weight="regular" color="var(--color-ink-2)" /></span>
          <span class:visible={saved}><BookmarkSimple size={20} weight="fill" color="var(--color-accent)" /></span>
        </span>
      </button>
      <DropdownMenu.Root bind:open={showMore}>
        <DropdownMenu.Trigger class="icon-btn" aria-label="More job actions">
          <DotsThree size={22} weight="bold" color={nativeIos ? "var(--color-ink-2)" : "var(--color-ink-3)"} />
        </DropdownMenu.Trigger>
        <DropdownMenu.Portal>
          <DropdownMenu.Content
            class="menu-surface job-more-menu"
            side="bottom"
            align="end"
            sideOffset={6}
            collisionPadding={12}
            strategy="fixed"
            preventScroll={false}
          >
            <DropdownMenu.Item
              class="menu-item"
              disabled={hidingCompany}
              onSelect={() => void hideCompany()}
            >
              {#if hidingCompany}<Spinner size={16} />{:else}<EyeSlash size={17} />{/if}
              <span>Hide {job?.company_name ?? "company"}</span>
            </DropdownMenu.Item>
            <DropdownMenu.Item class="menu-item" onSelect={() => { showReport = true; }}>
              <Flag size={17} />
              <span>Report listing</span>
            </DropdownMenu.Item>
            {#if $sessionAccess.isAdmin}
              <DropdownMenu.Item class="menu-item danger" onSelect={() => { showBlockConfirm = true; }}>
                <Trash size={17} />
                <span>Block for everyone</span>
              </DropdownMenu.Item>
            {/if}
          </DropdownMenu.Content>
        </DropdownMenu.Portal>
      </DropdownMenu.Root>
      </div>
    {/snippet}
  </ScreenNav>

  <div class="screen-content job-detail-content">
    {#if loading}
      <div class="page-loading" aria-busy="true"><Spinner size={22} label="Loading" /></div>
    {:else if error}
      <div class="job-detail-error" role="alert">
        <h1 class="h-display h-display-sm">This job didn&rsquo;t load</h1>
        <p>{error.toLowerCase().includes("not found") ? "The listing may have been removed since the alert was sent." : "Check your connection and try once more."}</p>
        <div class="button-cluster">
          <button class="btn-primary btn-accent" onclick={() => void loadJobDetail()}>Try again</button>
          <button class="btn-secondary" onclick={() => { if (!requestBack()) navigate("/"); }}>Back to jobs</button>
        </div>
      </div>
    {:else if job}
      <div class="job-detail-identity">
        <CompanyLogo name={job.company_name ?? "?"} domain={job.company_domain} size={52} />
        <div class="job-detail-heading">
          <div class="job-detail-company-line">
            <div class="section-label truncate">
              {job.company_name} · {jobTimingLabel(job)}
            </div>
            {#if job.closed_at}
              <div class="tag">closed</div>
            {/if}
          </div>
          <h1 class="h-display h-display-md job-detail-title" data-screen-title-anchor>
            {job.title}
          </h1>
        </div>
      </div>

      <div class="job-meta-strip job-detail-meta">
        {#if job.location}
          <div class="job-meta-item">
            <MapPin size={15} />
            <span>{job.location}</span>
          </div>
        {/if}
        {#if displaySalary}
          <div class="job-meta-item">
            <Money size={15} />
            <span>{displaySalary}</span>
          </div>
        {/if}
        {#if originalTiming}
          <div class="job-meta-item">
            <ClockCounterClockwise size={15} />
            <span>{originalTiming}</span>
          </div>
        {/if}
      </div>

      {#if quickFacts.length}
        <section class="job-match-panel" aria-labelledby="quick-facts-heading">
          <h2 id="quick-facts-heading">Quick facts</h2>
          <ul>
            {#each quickFacts as fact}
              <li><span aria-hidden="true"></span>{fact}</li>
            {/each}
          </ul>
        </section>
      {/if}

      <div class="job-state-actions">
          <button
            class="btn-secondary btn-action"
            class:completed={applied}
            disabled={applying || (!nativeIos && applied)}
            aria-pressed={nativeIos ? applied : undefined}
            onclick={markApplied}
          >
            {#if applyingPending}
              <Spinner />
            {:else}
              <span class="state-icon" aria-hidden="true">
                <span class:visible={!applied}><CheckCircle size={16} /></span>
                <span class:visible={applied}><CheckCircle size={16} weight="fill" /></span>
              </span>
            {/if}
            <span class="applied-label">
              <span class:visible={!applied} aria-hidden={applied}>I applied</span>
              <span class:visible={applied} aria-hidden={!applied}>Applied</span>
            </span>
          </button>
          <button
            class="btn-secondary btn-action"
            onclick={handleDismiss}
            disabled={dismissing}
          >
            {#if dismissing}<Spinner />{:else}<X size={15} />{/if}
            Not interested
          </button>
      </div>

      {#if descriptionPending}
        <div class="job-description-section">
          <h2 class="section-title job-description-heading">
            About the role
          </h2>
          <p class="job-description-lede with-action">
            Pulling the full posting now. This usually lands in a second or two.
          </p>
          <button class="btn-secondary btn-mini" onclick={() => { descriptionRefreshAttempts = 0; void loadJobDetail(true); }}>
            Check again
          </button>
        </div>
      {:else if sanitizedDescription}
        <div class="job-description-section">
          <h2 class="section-title job-description-heading">
            About the role
          </h2>
          <div class="job-description">
            {@html sanitizedDescription}
          </div>
          {#if job.url}
            <a
              href={job.url}
              target="_blank"
              rel="noopener noreferrer"
              class="text-link job-description-link"
            >
              Read full description
              <ArrowSquareOut size={13} />
            </a>
          {/if}
        </div>
      {:else if plainDescription}
        <div class="job-description-section">
          <h2 class="section-title job-description-heading">
            About the role
          </h2>
          <p class="job-description-lede">
            {plainDescription}
          </p>
          {#if job.url}
            <a
              href={job.url}
              target="_blank"
              rel="noopener noreferrer"
              class="text-link job-description-link"
            >
              Read full description
              <ArrowSquareOut size={13} />
            </a>
          {/if}
        </div>
      {:else}
        <div class="job-description-section">
          <h2 class="section-title job-description-heading">
            About the role
          </h2>
          <p class="job-description-lede with-action">
            We couldn’t pull the full job description yet. The original posting may still have it.
          </p>
          <div class="button-cluster">
            <button class="btn-secondary btn-mini" onclick={() => { descriptionRefreshAttempts = 0; void loadJobDetail(true); }}>
              Try again
            </button>
            {#if job.url}
              <a
                href={job.url}
                target="_blank"
                rel="noopener noreferrer"
                class="btn-secondary btn-mini button-link"
              >
                Open original
              </a>
            {/if}
          </div>
        </div>
      {/if}

    {/if}
  </div>
</div>

{#if !loading && !error && job}
  <div class="job-action-bar-wrap" data-nav-snapshot="exclude">
    <div class="job-action-bar">
      {#if job.url}
        <button
          type="button"
          class="btn-primary btn-accent btn-action button-link"
          onclick={openApplication}
          disabled={openingApplication}
        >
          {#if openingApplication}<Spinner />{:else}<ArrowSquareOut size={18} weight="regular" />{/if}
          Apply
        </button>
      {:else}
        <button class="btn-primary btn-accent btn-action" disabled>
          <ArrowSquareOut size={18} weight="regular" />
          Apply
        </button>
      {/if}
      <button
        class="btn-secondary btn-action"
        onclick={() => jobId && navigate(`/tailor/${jobId}`)}
      >
        <MagicWand size={16} />
        Tailor
      </button>
    </div>
  </div>
{/if}

<style>
  .job-detail-error {
    padding: 44px 4px;
  }

  .job-detail-error p {
    max-width: 34ch;
    margin: 8px 0 18px;
    color: var(--color-ink-3);
    font-size: var(--fs-sm);
    line-height: 1.5;
  }

  .job-detail-title {
    font-family: var(--font-pixel);
    font-weight: 400;
    letter-spacing: 0;
    line-height: 1.2;
  }

  :global(html.native-ios) .job-detail-title {
    font-family: var(--font-display);
    font-size: var(--fs-2xl);
    font-weight: 600;
    letter-spacing: -0.025em;
    line-height: 1.12;
  }

  .state-icon,
  .applied-label {
    display: grid;
    place-items: center;
  }

  .state-icon > span,
  .applied-label > span {
    grid-area: 1 / 1;
    display: grid;
    place-items: center;
    opacity: 0;
    transform: scale(0.72);
    transition:
      opacity var(--duration-instant) var(--ease-standard),
      transform var(--duration-instant) var(--ease-standard);
  }

  .applied-label > span {
    transform: translateY(3px);
  }

  .state-icon > span.visible,
  .applied-label > span.visible {
    opacity: 1;
    transform: none;
  }

  .btn-secondary.completed:disabled,
  .btn-secondary.completed:disabled:hover {
    opacity: 1;
    border-color: color-mix(in oklch, var(--color-accent) 46%, var(--color-line));
    background: var(--color-accent-soft);
    color: var(--color-accent-soft-ink);
  }

  .job-match-panel {
    padding: var(--space-4);
    margin-bottom: var(--space-4);
    border: 1px solid var(--color-line);
    border-radius: var(--radius-md);
    background: var(--color-bg-sunken);
  }

  .job-match-panel h2 {
    margin: 0 0 var(--space-2);
    color: var(--color-ink-3);
    font-size: var(--fs-sm);
    font-weight: 600;
  }

  .job-match-panel ul {
    padding: 0;
    margin: 0;
    display: grid;
    gap: var(--space-2);
    list-style: none;
  }

  .job-match-panel li {
    display: flex;
    align-items: baseline;
    gap: var(--space-2);
    color: var(--color-ink-2);
    font-size: var(--fs-sm);
    line-height: 1.35;
  }

  .job-match-panel li span {
    width: 5px;
    height: 5px;
    flex: none;
    border-radius: var(--radius-full);
    background: var(--color-accent);
    transform: translateY(-2px);
  }

</style>

{#if showReport}
  <Modal
    title="What looks wrong?"
    subtitle="Reports go to the pinkslip admin queue. They do not contact the employer."
    busy={reporting}
    onclose={() => (showReport = false)}
  >
    <div class="form-stack">
      {#if nativeIos}<label for="job-report-type">Reason</label>{/if}
      <select id="job-report-type" class="input-field" aria-label={nativeIos ? undefined : "Reason"} bind:value={reportType}>
        <option value="expired_listing">Listing is closed</option>
        <option value="incorrect_details">Details are incorrect</option>
        <option value="duplicate_listing">Duplicate listing</option>
        <option value="broken_source">Company source is broken</option>
        <option value="other">Something else</option>
      </select>
      {#if nativeIos}<label for="job-report-notes">Details <span class="field-optional">optional</span></label>{/if}
      <textarea
        id="job-report-notes"
        class="input-field textarea-field"
        rows="4"
        placeholder="Optional context"
        bind:value={reportNotes}
      ></textarea>
      <div class="action-row">
        <button class="btn-secondary" onclick={() => { showReport = false; }} disabled={reporting}>Cancel</button>
        <button class="btn-primary btn-accent flex-fill" onclick={submitReport} disabled={reporting}>
          {#if reporting}<Spinner />{/if}
          Send report
        </button>
      </div>
    </div>
  </Modal>
{/if}

{#if $sessionAccess.isAdmin && showBlockConfirm}
  <Modal
    title="Block this job?"
    busy={blocking}
    maxWidth={340}
    onclose={() => (showBlockConfirm = false)}
  >
    <p class="modal-copy">
      This will permanently remove <strong>{job?.title}</strong> from all users' feeds. It will never appear again, even in future polls.
      <br /><br />
      If you only want it gone from your own list, use <strong>Not interested</strong> instead.
    </p>
    <div class="stack-sm">
      <button
        class="btn-secondary full-width tall-control"
        onclick={() => { showBlockConfirm = false; handleDismiss(); }}
      >
        <X size={15} />
        Not interested
      </button>
      <button
        class="btn-secondary btn-danger full-width tall-control"
        disabled={blocking}
        onclick={handleBlock}
      >
        {#if blocking}<Spinner />{:else}<Trash size={15} />{/if}
        Block permanently
      </button>
      <button
        class="text-button"
        onclick={() => { showBlockConfirm = false; }}
      >
        Cancel
      </button>
    </div>
  </Modal>
{/if}

// apps/native/src/features/job-detail/JobDetail.tsx
import type { Job } from "@pinkslip/core/api";
import { parseJobDescription } from "@pinkslip/core/job-description";
import { formatJobLocation, normalizeSalaryText } from "@pinkslip/core/job-format";
import { jobOriginalTimingLabel, jobTimingLabel } from "@pinkslip/core/job-timing";
import {
  useApi, useBlockJob, useHideCompany, useHideJob, useJob, useMarkApplied, useMarkViewed, usePublicJob, useSaveJob, useSession,
  useUnmarkApplied, useUnsaveJob,
} from "@pinkslip/data";
import { useQueryClient } from "@tanstack/react-query";
import * as WebBrowser from "expo-web-browser";
import { router, Stack, usePathname } from "expo-router";
import { ArrowCounterClockwise, ArrowSquareOut, BookmarkSimple, CheckCircle, ClockCounterClockwise, MapPin, Money, WarningCircle } from "phosphor-react-native";
import { useEffect, useMemo, useRef, useState } from "react";
import { Alert, ScrollView, View } from "react-native";
import { StyleSheet, useUnistyles } from "react-native-unistyles";
import { Badge, Button, EmptyState, Heading, Skeleton, Spinner, Text, toast, UNDO_TOAST_DURATION } from "../../kit";
import { haptics } from "../../platform/haptics";
import { shareJob } from "../../platform/share";
import { ApplicationBrowser, type ApplicationRequest } from "../apply/ApplicationBrowser";
import { OutreachSheet } from "../apply/OutreachSheet";
import { CompanyLogo } from "../jobs/CompanyLogo";
import { cachedJob, type AnyJob } from "../jobs/cached-job";
import { useTrack } from "../jobs/track";
import { Description } from "./Description";
import { ReportSheet } from "./ReportSheet";

type DetailJob = AnyJob & Partial<Job>;

/** Which tab the job is open in, so related screens push onto the same stack. */
function useTabGroup(): "(jobs)" | "(library)" {
  return usePathname().startsWith("/library") ? "(library)" : "(jobs)";
}

/**
 * `JobDetail.svelte` for iOS: company, title, location, pay and dates, the
 * posting drawn from core's blocks. Apply and Save sit under the title (a
 * bottom bar would sit under the floating tab bar); everything else is in the
 * navigation bar's menu, as the web's single action bar groups it. Apply opens the posting
 * in Safari inside the app; closing it asks whether you applied.
 */
export function JobDetail({ jobId, outreachThread }: { jobId: string; outreachThread?: string }) {
  const queryClient = useQueryClient();
  const publicJob = usePublicJob(jobId);
  const personal = useJob(jobId);
  const seed = useMemo(() => cachedJob(queryClient, jobId), [queryClient, jobId]);
  const job: DetailJob | undefined = personal.data ?? publicJob.data ?? seed;
  const markViewed = useMarkViewed();
  const track = useTrack();

  useEffect(() => {
    markViewed(jobId);
    track("job_opened", { type: "job", id: jobId });
  }, [jobId, markViewed, track]);

  if (!job) {
    if (personal.isPending || publicJob.isPending) return <View style={styles.center}><Spinner label="Loading job" /></View>;
    if (personal.isError && publicJob.data === null) {
      return <View style={styles.center}><EmptyState icon={WarningCircle} title="This job isn't available" message="It may have closed or been removed." /></View>;
    }
    return <View style={styles.center}><EmptyState icon={WarningCircle} title="This job didn't load" message="Check your connection and try again."
      actions={<Button onPress={() => { void personal.refetch(); void publicJob.refetch(); }}>Try again</Button>} /></View>;
  }
  return <JobView job={job} full={Boolean(personal.data ?? publicJob.data)}
    pendingDescription={Boolean(personal.data?.content_pending && !personal.data.description && personal.isFetching)}
    onRetryDescription={() => void personal.refetch()} outreachThread={outreachThread} />;
}

function JobView({ job, full, pendingDescription, onRetryDescription, outreachThread }: {
  job: DetailJob;
  full: boolean;
  pendingDescription: boolean;
  onRetryDescription: () => void;
  outreachThread?: string;
}) {
  const { theme } = useUnistyles();
  const group = useTabGroup();
  const session = useSession().data;
  const features = session?.me?.features;
  const admin = Boolean(session?.me?.is_admin);
  const autoApply = Boolean(features?.auto_apply_enabled);
  const autoSubmit = Boolean(features?.auto_submit_enabled);
  const outreach = Boolean(features?.outreach_enabled);
  const save = useSaveJob();
  const unsave = useUnsaveJob();
  const markApplied = useMarkApplied();
  const unmarkApplied = useUnmarkApplied();
  const hideJob = useHideJob();
  const hideCompany = useHideCompany();
  const block = useBlockJob();
  const track = useTrack();
  const api = useApi();
  const [applying, setApplying] = useState<ApplicationRequest | null>(null);
  const [reporting, setReporting] = useState(false);
  const [emailing, setEmailing] = useState(Boolean(outreachThread && outreach));
  useEffect(() => { if (outreachThread && outreach) setEmailing(true); }, [outreachThread, outreach]);

  const blocks = useMemo(() => parseJobDescription(job.description, { title: job.title, companyName: job.company_name }),
    [job.description, job.title, job.company_name]);
  const salary = normalizeSalaryText(job.salary?.trim() ? job.salary : null);
  const location = formatJobLocation(job.location);
  const original = jobOriginalTimingLabel(job);
  const saved = Boolean(job.saved);
  const applied = Boolean(job.applied);
  const closed = Boolean(job.closed_at);
  const asJob = job as Job;

  // Announce when a pending posting arrives, or stops trying.
  const wasPending = useRef(pendingDescription);
  useEffect(() => {
    if (wasPending.current && !pendingDescription) toast.show({ message: blocks.length > 0 ? "The full posting loaded." : "The full posting isn't available yet.", dedupeKey: "posting" });
    wasPending.current = pendingDescription;
  }, [pendingDescription, blocks.length]);

  const setApplied = (value: boolean) => (value ? markApplied : unmarkApplied).mutate(asJob, {
    onSuccess: () => { if (value) haptics.success(); toast.success(value ? "Added to applied jobs" : "Removed from applied jobs"); },
    onError: () => toast.error("Couldn't update this job. Try again."),
  });
  const toggleSave = () => {
    haptics.tap();
    (saved ? unsave : save).mutate(job.id, { onError: () => toast.error("Couldn't update your saved jobs. Try again.") });
  };

  /** Safari opens over the app; closing it asks whether you applied, since
   * opening a posting alone never marks it applied. */
  const openApplication = async (url: string | null) => {
    const target = url ?? job.url;
    if (!target) return;
    track("apply_clicked", { type: "job", id: job.id, properties: autoApply ? { source: "prep" } : {} });
    await WebBrowser.openBrowserAsync(target, { presentationStyle: WebBrowser.WebBrowserPresentationStyle.PAGE_SHEET, controlsColor: theme.colors.accent });
    if (applied) return;
    Alert.alert("Did you apply?", `${job.title} at ${job.company_name}`, [
      { text: "Not yet", style: "cancel" },
      { text: "Yes, I applied", onPress: () => setApplied(true) },
    ]);
  };

  /** With auto-apply, the form opens in the application browser, which reads,
   * fills and (when allowed) submits it; a confirmed submission marks the job
   * applied. */
  const startAutoApply = async () => {
    track("apply_clicked", { type: "job", id: job.id, properties: { source: "auto_apply" } });
    const prepared = await api.apply.prepare(job.id).catch(() => null);
    const url = prepared?.apply_url ?? job.url;
    if (url) setApplying({ jobId: job.id, url, autoSubmit });
  };

  const leave = () => { if (router.canGoBack()) router.back(); };
  const notInterested = () => hideJob(job.id).then((hidden) => {
    leave();
    toast.show({ message: "Job hidden", duration: UNDO_TOAST_DURATION, action: { label: "Undo", run: () => hidden.undo().catch(() => { toast.error("Couldn't bring that job back."); }) } });
  }, () => toast.error("Couldn't hide this job. Try again."));
  const hideTheCompany = () => {
    if (!job.company_id) return;
    hideCompany(job.company_id).then((hidden) => {
      leave();
      toast.show({ message: `${job.company_name} hidden`, duration: UNDO_TOAST_DURATION, action: { label: "Undo", run: () => hidden.undo().catch(() => { toast.error("Couldn't bring that company back."); }) } });
    }, () => toast.error("Couldn't hide this company. Try again."));
  };
  const confirmBlock = () => Alert.alert("Block this job?", `This permanently removes ${job.title} at ${job.company_name} for everyone.`, [
    { text: "Cancel", style: "cancel" },
    { text: "Block job", style: "destructive", onPress: () => block.mutate(job.id, {
      onSuccess: () => { leave(); toast.success("Job blocked for everyone"); },
      onError: () => toast.error("Couldn't block this job. Try again."),
    }) },
  ]);

  const menu = [
    applied ? { label: "I didn't apply", icon: "arrow.uturn.backward", run: () => setApplied(false) } : { label: "I applied", icon: "checkmark.circle", run: () => setApplied(true) },
    !applied && { label: "Not interested", icon: "hand.thumbsdown", run: notInterested },
    outreach && { label: "Email recruiter", icon: "envelope", run: () => setEmailing(true) },
    { label: "Tailor resume", icon: "sparkles", run: () => router.push({ pathname: `/(tabs)/${group}/tailor/[jobId]`, params: { jobId: job.id } }) },
    { label: "Share", icon: "square.and.arrow.up", run: () => void shareJob(job) },
    job.company_id && { label: `Hide ${job.company_name}`, icon: "eye.slash", run: hideTheCompany },
    { label: "Report listing", icon: "flag", run: () => setReporting(true) },
    admin && { label: "Block for everyone", icon: "nosign", destructive: true, run: confirmBlock },
  ].filter((item): item is { label: string; icon: string; run: () => void; destructive?: boolean } => Boolean(item));

  return <View style={styles.fill}>
    <Stack.Screen options={{
      title: "",
      unstable_headerRightItems: () => [{
        type: "menu",
        label: "More job actions",
        icon: { type: "sfSymbol", name: "ellipsis" },
        menu: {
          items: menu.map((item) => ({ type: "action" as const, label: item.label, icon: { type: "sfSymbol" as const, name: item.icon as never }, destructive: item.destructive, onPress: item.run })),
        },
      }],
    }} />
    <ScrollView contentInsetAdjustmentBehavior="automatic" contentContainerStyle={styles.body}>
      <View style={styles.identity}>
        <CompanyLogo name={job.company_name} domain={job.company_domain} size={44} />
        <View style={styles.heading}>
          <View style={styles.companyLine}>
            <Text size="sm" weight="medium" tone="ink-2" truncate>{job.company_name} · {jobTimingLabel(job)}</Text>
            {closed && <Badge>Closed</Badge>}
          </View>
          <Heading variant="display-md">{job.title}</Heading>
        </View>
      </View>
      <View style={styles.meta}>
        {location && <Fact icon={MapPin} text={location} />}
        {salary && <Fact icon={Money} text={salary} />}
        {original && <Fact icon={ClockCounterClockwise} text={original} />}
      </View>
      <View style={styles.actionBlock}>
        <View style={styles.actions}>
          <Button icon={BookmarkSimple} iconFill={saved} accessibilityLabel={saved ? "Remove from saved jobs" : "Save job"} onPress={toggleSave}>{saved ? "Saved" : "Save"}</Button>
          <View style={styles.primary}>
            {applied ? <Button icon={CheckCircle} fullWidth disabled>Applied</Button>
              : <Button variant="primary" icon={ArrowSquareOut} fullWidth disabled={closed || !job.url}
                onPress={() => (autoApply ? void startAutoApply() : void openApplication(null))}>{closed ? "Listing closed" : "Apply"}</Button>}
          </View>
        </View>
        {(closed || !job.url) && !applied && <Text size="sm" tone="ink-3">{closed ? "This listing is closed." : "Application link unavailable."}</Text>}
      </View>
      <View style={styles.about}>
        <Heading>About the role</Heading>
        {!full ? <View style={styles.skeleton}><Skeleton width="92%" /><Skeleton width="86%" /><Skeleton width="64%" /></View>
          : pendingDescription ? <Text tone="ink-2">Pulling the full posting now. This usually lands in a second or two.</Text>
          : blocks.length > 0 ? <Description blocks={blocks} />
          : <View style={styles.missing}>
            <Text tone="ink-2">We couldn't pull the full job description yet. The original posting may still have it.</Text>
            <Button size="compact" icon={ArrowCounterClockwise} onPress={onRetryDescription}>Try again</Button>
          </View>}
      </View>
    </ScrollView>
    {autoApply && <ApplicationBrowser request={applying} onClose={() => setApplying(null)}
      onSubmitted={() => markApplied.mutate(asJob, { onSuccess: () => { haptics.success(); toast.success("Added to applied jobs"); } })} />}
    <ReportSheet jobId={job.id} open={reporting} onOpenChange={setReporting} />
    {outreach && <OutreachSheet jobId={job.id} companyName={job.company_name} threadId={outreachThread ?? null} open={emailing} onOpenChange={setEmailing} />}
  </View>;
}

function Fact({ icon: Glyph, text }: { icon: typeof MapPin; text: string }) {
  const { theme } = useUnistyles();
  return <View style={styles.fact}><Glyph size={15} color={theme.colors["ink-3"]} /><Text size="sm" tone="ink-2">{text}</Text></View>;
}

const styles = StyleSheet.create((theme) => ({
  fill: { flex: 1, backgroundColor: theme.colors.bg },
  center: { flex: 1, justifyContent: "center", backgroundColor: theme.colors.bg },
  body: { padding: theme.gutter, gap: theme.space["5"], paddingBottom: theme.space["10"] },
  identity: { flexDirection: "row", gap: theme.space["3"], alignItems: "flex-start" },
  heading: { flex: 1, gap: theme.space["1"] },
  companyLine: { flexDirection: "row", alignItems: "center", gap: theme.space["2"] },
  meta: { gap: theme.space["2"] },
  fact: { flexDirection: "row", alignItems: "center", gap: theme.space["2"] },
  about: { gap: theme.space["3"] },
  skeleton: { gap: theme.space["2"] },
  missing: { gap: theme.space["3"], alignItems: "flex-start" },
  actionBlock: { gap: theme.space["2"] },
  actions: { flexDirection: "row", gap: theme.space["3"] },
  primary: { flex: 1 },
}));
