// apps/webapp/src/kit/save-status/SaveStatus.tsx
import { Check, CircleNotch, WarningCircle } from "@phosphor-icons/react";
import { VisuallyHidden } from "../visually-hidden/VisuallyHidden";
import styles from "./SaveStatus.module.css";

export type SavePhase = "clean" | "dirty" | "saving" | "saved" | "error";

export interface SaveStatusProps {
  phase: SavePhase;
  savedLabel?: string;
  /** Icon only for saving and saved; the words stay for screen readers. */
  compact?: boolean;
  errorMessage?: string | null;
  onRetry?: () => void;
}

const messages: Record<SavePhase, string> = {
  clean: "",
  dirty: "Unsaved",
  saving: "Saving…",
  saved: "Saved",
  error: "Not saved",
};

export function SaveStatus({ phase, savedLabel = "Saved", compact, errorMessage, onRetry }: SaveStatusProps) {
  const message = phase === "saved" ? savedLabel : messages[phase];
  const hideLabel = compact && (phase === "saving" || phase === "saved");
  const live = phase !== "error";

  return <span className={styles.root} data-phase={phase} data-compact={compact || undefined}>
    <span
      className={styles.content}
      data-visible={message.length > 0 || undefined}
      role={live ? "status" : undefined}
      aria-live={live ? "polite" : undefined}
      aria-atomic={live ? true : undefined}
    >
      {phase === "saving" && <CircleNotch className={styles.spinner} size={13} aria-hidden />}
      {phase === "saved" && <Check size={13} aria-hidden />}
      {phase === "error" && <WarningCircle size={13} aria-hidden />}
      {hideLabel ? <VisuallyHidden>{message}</VisuallyHidden> : <span>{message}</span>}
    </span>
    {phase === "error" && onRetry && <button
      type="button"
      className={styles.retry}
      aria-label={errorMessage ? `Save failed: ${errorMessage}. Retry saving` : "Save failed. Retry saving"}
      onClick={onRetry}
    >Retry</button>}
  </span>;
}

// frontend/src/components/SaveStatus.svelte
<script lang="ts">
  import Check from "phosphor-svelte/lib/Check";
  import CircleNotch from "phosphor-svelte/lib/CircleNotch";
  import WarningCircle from "phosphor-svelte/lib/WarningCircle";
  import type { SavePhase } from "../lib/task-presentation.svelte";

  let {
    phase,
    savedLabel = "Saved",
  }: {
    phase: SavePhase;
    savedLabel?: string;
  } = $props();

  let message = $derived(
    phase === "dirty" ? "Unsaved"
      : phase === "saving" ? "Saving"
        : phase === "saved" ? savedLabel
          : phase === "error" ? "Couldn’t save"
            : ""
  );
</script>

<span class="save-status" class:error={phase === "error"} role="status" aria-live="polite" aria-atomic="true">
  <span class="save-status-content" class:visible={message.length > 0}>
    {#if phase === "saving"}
      <CircleNotch class="save-status-spinner" size={13} />
    {:else if phase === "saved"}
      <Check size={13} />
    {:else if phase === "error"}
      <WarningCircle size={13} />
    {/if}
    <span>{message}</span>
  </span>
</span>

<style>
  .save-status {
    min-width: 104px;
    min-height: 20px;
    display: inline-flex;
    align-items: center;
    justify-content: flex-end;
    color: var(--color-ink-4);
    font-size: var(--fs-xs);
    font-variant-numeric: tabular-nums;
  }

  .save-status.error {
    color: var(--color-bad);
  }

  .save-status-content {
    display: inline-flex;
    align-items: center;
    gap: var(--space-1);
    opacity: 0;
    transform: translateY(2px);
    transition:
      opacity var(--duration-fast) var(--ease-standard),
      transform var(--duration-fast) var(--ease-standard);
  }

  .save-status-content.visible {
    opacity: 1;
    transform: translateY(0);
  }

  :global(.save-status-spinner) {
    animation: save-status-spin 0.9s linear infinite;
  }

  @keyframes save-status-spin {
    to { transform: rotate(360deg); }
  }
</style>
