// packages/client/src/pages/JobDetail.svelte
<script lang="ts">
  import { onDestroy } from "svelte";
  import { navigate } from "../router";
  import { requestBack } from "../lib/nav-back";
  import { api, type Job } from "../lib/api";
  import { errorMessage } from "../lib/utils";
  import { shareLink } from "../lib/share";
  import { feed } from "../lib/feed-store.svelte";
  import { sessionAccess } from "../lib/session-access";
  import { markViewed } from "../lib/viewed";
  import { feedback } from "../lib/feedback.svelte";
  import { applicationIntent } from "../lib/application-intent.svelte";
  import { jobOriginalTimingLabel, jobTimingLabel } from "../lib/job-timing";
  import { presentPending } from "../lib/task-presentation.svelte";
  import { isIosApp } from "../lib/platform";
  import { roleLabel } from "../../../../shared/search-profile";
  import {
    extractPlainTextFromHtml,
    extractSalaryFromHtml,
    normalizeSalaryText,
    sanitizeJobDescriptionHtml,
  } from "../lib/job-content";
  import { DropdownMenu } from "bits-ui";
  import CompanyLogo from "../components/CompanyLogo.svelte";
  import Modal from "../components/Modal.svelte";
  import ScreenNav from "../components/ScreenNav.svelte";
  import BookmarkSimple from "phosphor-svelte/lib/BookmarkSimple";
  import MapPin from "phosphor-svelte/lib/MapPin";
  import Money from "phosphor-svelte/lib/Money";
  import ClockCounterClockwise from "phosphor-svelte/lib/ClockCounterClockwise";
  import ArrowSquareOut from "phosphor-svelte/lib/ArrowSquareOut";
  import Export from "phosphor-svelte/lib/Export";
  import DotsThree from "phosphor-svelte/lib/DotsThree";
  import CheckCircle from "phosphor-svelte/lib/CheckCircle";
  import X from "phosphor-svelte/lib/X";
  import Trash from "phosphor-svelte/lib/Trash";
  import MagicWand from "phosphor-svelte/lib/MagicWand";
  import EyeSlash from "phosphor-svelte/lib/EyeSlash";
  import Flag from "phosphor-svelte/lib/Flag";
  import Spinner from "../components/Spinner.svelte";

  let { jobId = null }: { jobId?: string | null } = $props();

  let job = $state<Job | null>(null);
  let loading: boolean = $state(true);
  let error: string | null = $state(null);
  let dismissing: boolean = $state(false);
  let saved: boolean = $state(false);
  let applied: boolean = $state(false);
  let applying: boolean = $state(false);
  let applyingPending: boolean = $state(false);
  let openingApplication: boolean = $state(false);
  let showBlockConfirm: boolean = $state(false);
  let showMore: boolean = $state(false);
  let blocking: boolean = $state(false);
  let descriptionPending: boolean = $state(false);
  let hidingCompany: boolean = $state(false);
  let showReport: boolean = $state(false);
  let reportType: string = $state("incorrect_details");
  let reportNotes: string = $state("");
  let reporting: boolean = $state(false);
  let openedJobId: string | null = null;
  let descriptionRefreshTimer: number | null = null;
  let descriptionRefreshAttempts = 0;

  const MAX_DESCRIPTION_REFRESH_ATTEMPTS = 5;
  const nativeIos = isIosApp();

  function clearDescriptionRefreshTimer() {
    if (descriptionRefreshTimer !== null) {
      window.clearTimeout(descriptionRefreshTimer);
      descriptionRefreshTimer = null;
    }
  }

  function removeFromFeedStore(id: string) {
    feed.jobs = feed.jobs.filter((item) => item.id !== id);
  }

  function restoreToFeedStore(nextJob: Job) {
    if (!feed.jobs.some((item) => item.id === nextJob.id)) {
      feed.jobs = [nextJob, ...feed.jobs];
    }
  }

  function syncJobState(nextJob: Job) {
    job = nextJob;
    saved = Boolean(nextJob?.saved);
    applied = Boolean(nextJob?.applied);
    descriptionPending = Boolean(nextJob?.content_pending && !nextJob?.description);
  }

  async function loadJobDetail(silent = false) {
    if (!jobId) return;
    if (!silent) {
      loading = true;
      error = null;
    }

    try {
      const nextJob = await api.jobs.get(jobId);
      syncJobState(nextJob);
      if (openedJobId !== jobId) {
        openedJobId = jobId;
        markViewed(jobId);
        void api.interactions.event({
          event_name: "job_opened",
          entity_type: "job",
          entity_id: jobId,
          properties: {},
        }).catch(() => undefined);
      }

      if (descriptionPending && descriptionRefreshAttempts < MAX_DESCRIPTION_REFRESH_ATTEMPTS) {
        clearDescriptionRefreshTimer();
        descriptionRefreshTimer = window.setTimeout(async () => {
          descriptionRefreshAttempts += 1;
          await loadJobDetail(true);
        }, nextJob.content_refresh_after_ms ?? 1500);
      } else if (descriptionPending) {
        descriptionPending = false;
        clearDescriptionRefreshTimer();
      } else if (!descriptionPending) {
        clearDescriptionRefreshTimer();
      }
    } catch (e) {
      if (!silent || !job) {
        error = errorMessage(e);
      }
    } finally {
      loading = false;
    }
  }

  $effect(() => {
    if (!jobId) return;
    applied = false;
    descriptionRefreshAttempts = 0;
    clearDescriptionRefreshTimer();
    void loadJobDetail();

    return () => {
      clearDescriptionRefreshTimer();
    };
  });

  onDestroy(() => {
    clearDescriptionRefreshTimer();
  });

  async function markApplied() {
    if (!jobId || !job || applying || (!nativeIos && applied)) return;
    applying = true;
    try {
      if (nativeIos && applied) {
        const restored = await presentPending(
          () => api.jobs.unmarkApplied(jobId),
          (pending) => { applyingPending = pending; },
        );
        applied = false;
        job = restored;
        restoreToFeedStore(restored);
        feedback.success("Removed from applied jobs");
        return;
      }
      await presentPending(
        () => api.jobs.markApplied(jobId),
        (pending) => { applyingPending = pending; },
      );
      applied = true;
      removeFromFeedStore(jobId);
      feedback.success("Added to applied jobs");
    } catch (e) {
      feedback.error(errorMessage(e, "Could not mark this job as applied."));
    } finally {
      applying = false;
      applyingPending = false;
    }
  }

  async function openApplication() {
    if (!job?.url || openingApplication) return;
    openingApplication = true;
    void api.interactions.event({
      event_name: "apply_clicked",
      entity_type: "job",
      entity_id: jobId ?? undefined,
      properties: {},
    }).catch(() => undefined);
    try {
      await applicationIntent.open(job);
    } catch (e) {
      feedback.error(errorMessage(e, "Could not open the application page."));
    } finally {
      openingApplication = false;
    }
  }

  async function handleDismiss() {
    if (!jobId || !job) return;
    const dismissedJob = job;
    dismissing = true;
    try {
      await api.jobs.dismiss(jobId);
      removeFromFeedStore(jobId);
      navigate("/");
      if (nativeIos) {
        feedback.show({
          message: "Job hidden from your feed",
          action: {
            label: "Undo",
            run: async () => {
              const restored = await api.jobs.undismiss(dismissedJob.id);
              restoreToFeedStore(restored);
            },
          },
        });
      }
    } catch (e) {
      feedback.error(errorMessage(e, "Could not dismiss this job."));
      dismissing = false;
    }
  }

  function shareJob() {
    if (!job) return;
    void shareLink({
      title: `${job.title} · ${job.company_name}`,
      text: `${job.title} at ${job.company_name}`,
      url: job.url || window.location.href,
    });
  }

  async function toggleSave() {
    if (!jobId) return;
    const newVal = !saved;
    saved = newVal;
    try {
      if (newVal) {
        await api.savedJobs.save(jobId);
      } else {
        await api.savedJobs.unsave(jobId);
      }
    } catch (e) {
      saved = !newVal;
      feedback.error(errorMessage(e, "Could not update your saved jobs."));
    }
  }

  async function handleBlock() {
    if (!jobId || blocking) return;
    blocking = true;
    try {
      await api.jobs.block(jobId);
      removeFromFeedStore(jobId);
      navigate("/");
    } catch (e) {
      feedback.error(errorMessage(e, "Could not block this job."));
      blocking = false;
    }
  }

  async function hideCompany() {
    if (!job?.company_id || hidingCompany) return;
    const companyId = job.company_id;
    const previousJobs = [...feed.jobs];
    hidingCompany = true;
    try {
      await api.companies.block(companyId);
      feed.jobs = feed.jobs.filter((item) => item.company_id !== job?.company_id);
      navigate("/");
      if (nativeIos) {
        feedback.show({
          message: `${job.company_name} hidden`,
          action: {
            label: "Undo",
            run: async () => {
              await api.companies.restore(companyId);
              feed.jobs = previousJobs;
            },
          },
        });
      }
    } catch (e) {
      feedback.error(errorMessage(e, "Could not hide this company."));
      hidingCompany = false;
    }
  }

  async function submitReport() {
    if (!jobId || reporting) return;
    reporting = true;
    try {
      await api.interactions.report({
        job_id: jobId,
        report_type: reportType,
        notes: reportNotes,
      });
      showReport = false;
      reportNotes = "";
      feedback.success("Report sent. Thanks for helping keep listings accurate.");
    } catch (e) {
      feedback.error(errorMessage(e, "Could not send that report."));
    } finally {
      reporting = false;
    }
  }

  let extractedSalary = $derived(job?.description ? extractSalaryFromHtml(job.description) : null);
  let displaySalary = $derived(normalizeSalaryText(
    job?.salary?.trim() ? job.salary : extractedSalary
  ));
  let originalTiming = $derived(job ? jobOriginalTimingLabel(job) : null);
  let quickFacts = $derived.by(() => {
    if (!job) return [];
    const details: string[] = [];
    if (nativeIos) {
      if (job.sponsorship_available === true) details.push("Sponsorship available");
      if (!displaySalary) details.push("Salary not listed");
      return details;
    }
    if (job.match_fact) details.push(job.match_fact);
    const specialty = job.specialties?.[0];
    if (specialty) details.push(`${roleLabel(specialty)} role`);
    if (job.sponsorship_available === true) details.push("Sponsorship available");
    if (!displaySalary) details.push("Salary not listed");
    if (job.evergreen) details.push("Evergreen listing");
    if (!job.posted_at) details.push("Post date unavailable");
    return [...new Set(details)].slice(0, 4);
  });
  let sanitizedDescription = $derived(job?.description ? sanitizeJobDescriptionHtml(job.description, {
    title: job.title,
    companyName: job.company_name,
  }) : "");
  let plainDescription = $derived.by(() => {
    return extractPlainTextFromHtml(job?.description);
  });

</script>

<div class="page pushed-screen">
  <ScreenNav
    title={nativeIos ? job?.title ?? "" : ""}
    collapsible={Boolean(job)}
    backLabel="Back to jobs"
    onBack={() => { if (!requestBack()) navigate("/"); }}
  >
    {#snippet trailing()}
      <div class="job-header-actions">
      <button class="icon-btn" aria-label="Share job" onclick={shareJob}>
        <Export size={19} color={nativeIos ? "var(--color-ink-2)" : "var(--color-ink-3)"} />
      </button>
      <button
        class="icon-btn"
        aria-label={saved ? "Remove from saved jobs" : "Save job"}
        aria-pressed={saved}
        onclick={toggleSave}
      >
        <span class="state-icon" aria-hidden="true">
          <span class:visible={!saved}><BookmarkSimple size={20} weight="regular" color="var(--color-ink-2)" /></span>
          <span class:visible={saved}><BookmarkSimple size={20} weight="fill" color="var(--color-accent)" /></span>
        </span>
      </button>
      <DropdownMenu.Root bind:open={showMore}>
        <DropdownMenu.Trigger class="icon-btn" aria-label="More job actions">
          <DotsThree size={22} weight="bold" color={nativeIos ? "var(--color-ink-2)" : "var(--color-ink-3)"} />
        </DropdownMenu.Trigger>
        <DropdownMenu.Portal>
          <DropdownMenu.Content
            class="menu-surface job-more-menu"
            side="bottom"
            align="end"
            sideOffset={6}
            collisionPadding={12}
            strategy="fixed"
            preventScroll={false}
          >
            <DropdownMenu.Item
              class="menu-item"
              disabled={hidingCompany}
              onSelect={() => void hideCompany()}
            >
              {#if hidingCompany}<Spinner size={16} />{:else}<EyeSlash size={17} />{/if}
              <span>Hide {job?.company_name ?? "company"}</span>
            </DropdownMenu.Item>
            <DropdownMenu.Item class="menu-item" onSelect={() => { showReport = true; }}>
              <Flag size={17} />
              <span>Report listing</span>
            </DropdownMenu.Item>
            {#if $sessionAccess.isAdmin}
              <DropdownMenu.Item class="menu-item danger" onSelect={() => { showBlockConfirm = true; }}>
                <Trash size={17} />
                <span>Block for everyone</span>
              </DropdownMenu.Item>
            {/if}
          </DropdownMenu.Content>
        </DropdownMenu.Portal>
      </DropdownMenu.Root>
      </div>
    {/snippet}
  </ScreenNav>

  <div class="screen-content job-detail-content">
    {#if loading}
      <div class="page-loading" aria-busy="true"><Spinner size={22} label="Loading" /></div>
    {:else if error}
      <div class="job-detail-error" role="alert">
        <h1 class="h-display h-display-sm">This job didn&rsquo;t load</h1>
        <p>{error.toLowerCase().includes("not found") ? "The listing may have been removed since the alert was sent." : "Check your connection and try once more."}</p>
        <div class="button-cluster">
          <button class="btn-primary btn-accent" onclick={() => void loadJobDetail()}>Try again</button>
          <button class="btn-secondary" onclick={() => { if (!requestBack()) navigate("/"); }}>Back to jobs</button>
        </div>
      </div>
    {:else if job}
      <div class="job-detail-identity">
        <CompanyLogo name={job.company_name ?? "?"} domain={job.company_domain} size={52} />
        <div class="job-detail-heading">
          <div class="job-detail-company-line">
            <div class="section-label truncate">
              {job.company_name} · {jobTimingLabel(job)}
            </div>
            {#if job.closed_at}
              <div class="tag">closed</div>
            {/if}
          </div>
          <h1 class="h-display h-display-md job-detail-title" data-screen-title-anchor>
            {job.title}
          </h1>
        </div>
      </div>

      <div class="job-meta-strip job-detail-meta">
        {#if job.location}
          <div class="job-meta-item">
            <MapPin size={15} />
            <span>{job.location}</span>
          </div>
        {/if}
        {#if displaySalary}
          <div class="job-meta-item">
            <Money size={15} />
            <span>{displaySalary}</span>
          </div>
        {/if}
        {#if originalTiming}
          <div class="job-meta-item">
            <ClockCounterClockwise size={15} />
            <span>{originalTiming}</span>
          </div>
        {/if}
      </div>

      {#if quickFacts.length}
        <section class="job-match-panel" aria-labelledby="quick-facts-heading">
          <h2 id="quick-facts-heading">Quick facts</h2>
          <ul>
            {#each quickFacts as fact}
              <li><span aria-hidden="true"></span>{fact}</li>
            {/each}
          </ul>
        </section>
      {/if}

      <div class="job-state-actions">
          <button
            class="btn-secondary btn-action"
            class:completed={applied}
            disabled={applying || (!nativeIos && applied)}
            aria-pressed={nativeIos ? applied : undefined}
            onclick={markApplied}
          >
            {#if applyingPending}
              <Spinner />
            {:else}
              <span class="state-icon" aria-hidden="true">
                <span class:visible={!applied}><CheckCircle size={16} /></span>
                <span class:visible={applied}><CheckCircle size={16} weight="fill" /></span>
              </span>
            {/if}
            <span class="applied-label">
              <span class:visible={!applied} aria-hidden={applied}>I applied</span>
              <span class:visible={applied} aria-hidden={!applied}>Applied</span>
            </span>
          </button>
          <button
            class="btn-secondary btn-action"
            onclick={handleDismiss}
            disabled={dismissing}
          >
            {#if dismissing}<Spinner />{:else}<X size={15} />{/if}
            Not interested
          </button>
      </div>

      {#if descriptionPending}
        <div class="job-description-section">
          <h2 class="section-title job-description-heading">
            About the role
          </h2>
          <p class="job-description-lede with-action">
            Pulling the full posting now. This usually lands in a second or two.
          </p>
          <button class="btn-secondary btn-mini" onclick={() => { descriptionRefreshAttempts = 0; void loadJobDetail(true); }}>
            Check again
          </button>
        </div>
      {:else if sanitizedDescription}
        <div class="job-description-section">
          <h2 class="section-title job-description-heading">
            About the role
          </h2>
          <div class="job-description">
            {@html sanitizedDescription}
          </div>
          {#if job.url}
            <a
              href={job.url}
              target="_blank"
              rel="noopener noreferrer"
              class="text-link job-description-link"
            >
              Read full description
              <ArrowSquareOut size={13} />
            </a>
          {/if}
        </div>
      {:else if plainDescription}
        <div class="job-description-section">
          <h2 class="section-title job-description-heading">
            About the role
          </h2>
          <p class="job-description-lede">
            {plainDescription}
          </p>
          {#if job.url}
            <a
              href={job.url}
              target="_blank"
              rel="noopener noreferrer"
              class="text-link job-description-link"
            >
              Read full description
              <ArrowSquareOut size={13} />
            </a>
          {/if}
        </div>
      {:else}
        <div class="job-description-section">
          <h2 class="section-title job-description-heading">
            About the role
          </h2>
          <p class="job-description-lede with-action">
            We couldn’t pull the full job description yet. The original posting may still have it.
          </p>
          <div class="button-cluster">
            <button class="btn-secondary btn-mini" onclick={() => { descriptionRefreshAttempts = 0; void loadJobDetail(true); }}>
              Try again
            </button>
            {#if job.url}
              <a
                href={job.url}
                target="_blank"
                rel="noopener noreferrer"
                class="btn-secondary btn-mini button-link"
              >
                Open original
              </a>
            {/if}
          </div>
        </div>
      {/if}

    {/if}
  </div>
</div>

{#if !loading && !error && job}
  <div class="job-action-bar-wrap" data-nav-snapshot="exclude">
    <div class="job-action-bar">
      {#if job.url}
        <button
          type="button"
          class="btn-primary btn-accent btn-action button-link"
          onclick={openApplication}
          disabled={openingApplication}
        >
          {#if openingApplication}<Spinner />{:else}<ArrowSquareOut size={18} weight="regular" />{/if}
          Apply
        </button>
      {:else}
        <button class="btn-primary btn-accent btn-action" disabled>
          <ArrowSquareOut size={18} weight="regular" />
          Apply
        </button>
      {/if}
      <button
        class="btn-secondary btn-action"
        onclick={() => jobId && navigate(`/tailor/${jobId}`)}
      >
        <MagicWand size={16} />
        Tailor
      </button>
    </div>
  </div>
{/if}

<style>
  .job-detail-error {
    padding: 44px 4px;
  }

  .job-detail-error p {
    max-width: 34ch;
    margin: 8px 0 18px;
    color: var(--color-ink-3);
    font-size: var(--fs-sm);
    line-height: 1.5;
  }

  .job-detail-title {
    font-family: var(--font-pixel);
    font-weight: 400;
    letter-spacing: 0;
    line-height: 1.2;
  }

  :global(html.native-ios) .job-detail-title {
    font-family: var(--font-display);
    font-size: var(--fs-2xl);
    font-weight: 600;
    letter-spacing: -0.025em;
    line-height: 1.12;
  }

  .state-icon,
  .applied-label {
    display: grid;
    place-items: center;
  }

  .state-icon > span,
  .applied-label > span {
    grid-area: 1 / 1;
    display: grid;
    place-items: center;
    opacity: 0;
    transform: scale(0.72);
    transition:
      opacity var(--duration-instant) var(--ease-standard),
      transform var(--duration-instant) var(--ease-standard);
  }

  .applied-label > span {
    transform: translateY(3px);
  }

  .state-icon > span.visible,
  .applied-label > span.visible {
    opacity: 1;
    transform: none;
  }

  .btn-secondary.completed:disabled,
  .btn-secondary.completed:disabled:hover {
    opacity: 1;
    border-color: color-mix(in oklch, var(--color-accent) 46%, var(--color-line));
    background: var(--color-accent-soft);
    color: var(--color-accent-soft-ink);
  }

  .job-match-panel {
    padding: var(--space-4);
    margin-bottom: var(--space-4);
    border: 1px solid var(--color-line);
    border-radius: var(--radius-md);
    background: var(--color-bg-sunken);
  }

  .job-match-panel h2 {
    margin: 0 0 var(--space-2);
    color: var(--color-ink-3);
    font-size: var(--fs-sm);
    font-weight: 600;
  }

  .job-match-panel ul {
    padding: 0;
    margin: 0;
    display: grid;
    gap: var(--space-2);
    list-style: none;
  }

  .job-match-panel li {
    display: flex;
    align-items: baseline;
    gap: var(--space-2);
    color: var(--color-ink-2);
    font-size: var(--fs-sm);
    line-height: 1.35;
  }

  .job-match-panel li span {
    width: 5px;
    height: 5px;
    flex: none;
    border-radius: var(--radius-full);
    background: var(--color-accent);
    transform: translateY(-2px);
  }

</style>

{#if showReport}
  <Modal
    title="What looks wrong?"
    subtitle="Reports go to the pinkslip admin queue. They do not contact the employer."
    busy={reporting}
    onclose={() => (showReport = false)}
  >
    <div class="form-stack">
      {#if nativeIos}<label for="job-report-type">Reason</label>{/if}
      <select id="job-report-type" class="input-field" aria-label={nativeIos ? undefined : "Reason"} bind:value={reportType}>
        <option value="expired_listing">Listing is closed</option>
        <option value="incorrect_details">Details are incorrect</option>
        <option value="duplicate_listing">Duplicate listing</option>
        <option value="broken_source">Company source is broken</option>
        <option value="other">Something else</option>
      </select>
      {#if nativeIos}<label for="job-report-notes">Details <span class="field-optional">optional</span></label>{/if}
      <textarea
        id="job-report-notes"
        class="input-field textarea-field"
        rows="4"
        placeholder="Optional context"
        bind:value={reportNotes}
      ></textarea>
      <div class="action-row">
        <button class="btn-secondary" onclick={() => { showReport = false; }} disabled={reporting}>Cancel</button>
        <button class="btn-primary btn-accent flex-fill" onclick={submitReport} disabled={reporting}>
          {#if reporting}<Spinner />{/if}
          Send report
        </button>
      </div>
    </div>
  </Modal>
{/if}

{#if $sessionAccess.isAdmin && showBlockConfirm}
  <Modal
    title="Block this job?"
    busy={blocking}
    maxWidth={340}
    onclose={() => (showBlockConfirm = false)}
  >
    <p class="modal-copy">
      This will permanently remove <strong>{job?.title}</strong> from all users' feeds. It will never appear again, even in future polls.
      <br /><br />
      If you only want it gone from your own list, use <strong>Not interested</strong> instead.
    </p>
    <div class="stack-sm">
      <button
        class="btn-secondary full-width tall-control"
        onclick={() => { showBlockConfirm = false; handleDismiss(); }}
      >
        <X size={15} />
        Not interested
      </button>
      <button
        class="btn-secondary btn-danger full-width tall-control"
        disabled={blocking}
        onclick={handleBlock}
      >
        {#if blocking}<Spinner />{:else}<Trash size={15} />{/if}
        Block permanently
      </button>
      <button
        class="text-button"
        onclick={() => { showBlockConfirm = false; }}
      >
        Cancel
      </button>
    </div>
  </Modal>
{/if}

// apps/webapp/src/features/job-detail/JobDetail.tsx
import { useNavigate, useParams, useSearch } from "@tanstack/react-router";
import { useQueryClient } from "@tanstack/react-query";
import { forwardRef, useEffect, useMemo, useState } from "react";
import {
  ArrowCounterClockwise, ArrowSquareOut, BookmarkSimple, CaretDown, CaretUp, CheckCircle, ClockCounterClockwise,
  DotsThree, EyeSlash, Flag, MapPin, Money, Prohibit, ShareNetwork, Sparkle, ThumbsDown, type IconProps,
} from "@phosphor-icons/react";
import type { Job } from "@pinkslip/core/api";
import { parseJobDescription } from "@pinkslip/core/job-description";
import { formatJobLocation, normalizeSalaryText } from "@pinkslip/core/job-format";
import { jobOriginalTimingLabel, jobTimingLabel } from "@pinkslip/core/job-timing";
import { roleLabel } from "@pinkslip/domain/search-profile";
import {
  useBlockJob, useHideCompany, useHideJob, useJob, useMarkApplied, useMarkViewed, usePublicJob, useSaveJob,
  useUnmarkApplied, useUnsaveJob,
} from "@pinkslip/data";
import {
  AlertDialog, Badge, Button, Heading, IconButton, Menu, MenuItem, MenuSeparator, Skeleton, Text, toast,
  UNDO_TOAST_DURATION,
} from "../../kit";
import { CompanyLogo } from "../jobs/CompanyLogo";
import { cachedJob, type AnyJob } from "../jobs/cached-job";
import { usePromoteVisitor, useSessionAccess } from "../jobs/useJobActions";
import type { JobOrigin } from "../jobs/JobRow";
import { rememberedFeedSearch } from "../feed/criteria";
import { jobRoot } from "../navigation/back-target";
import { useNeighbours } from "../split/neighbours";
import { PageFailure, PageLoading } from "../states/LoadStates";
import { JobNotFoundPage } from "../states/PageStates";
import { openApplication } from "./application-return";
import { useTrack } from "../jobs/track";
import { Description } from "./Description";
import { ReportDialog } from "./ReportDialog";
import styles from "./JobDetail.module.css";

type DetailJob = AnyJob & Partial<Job>;

/** The Save button's icon once saved: the same bookmark, filled. */
const SavedBookmark = forwardRef<SVGSVGElement, IconProps>((props, ref) => <BookmarkSimple ref={ref} {...props} weight="fill" />);
SavedBookmark.displayName = "SavedBookmark";

function quickFacts(job: DetailJob, salary: string | null): string[] {
  const facts: string[] = [];
  if (job.match_fact) facts.push(job.match_fact);
  const specialty = job.specialties?.[0];
  if (specialty) facts.push(`${roleLabel(specialty)} role`);
  if (job.sponsorship_available === true) facts.push("Sponsorship available");
  if (!salary) facts.push("Salary not listed");
  if (job.evergreen) facts.push("Evergreen listing");
  if (!job.posted_at) facts.push("Post date unavailable");
  return [...new Set(facts)].slice(0, 4);
}

async function share(job: DetailJob) {
  const url = `${window.location.origin}/jobs/${encodeURIComponent(job.id)}`;
  const data = { title: `${job.title} · ${job.company_name}`, text: `${job.title} at ${job.company_name}`, url };
  if (navigator.share && navigator.canShare?.(data) !== false) {
    await navigator.share(data).catch(() => undefined);
    return;
  }
  try {
    await navigator.clipboard.writeText(url);
    toast.success("Link copied");
  } catch {
    toast.error("Couldn't copy the link.");
  }
}

/**
 * `JobDetail.svelte` for the web, with its actions in one place (D17): the
 * company and title, location, salary and dates, quick facts, the posting,
 * and one action bar (Apply, Save, and a menu with everything else) pinned
 * to the bottom. Anyone can read it: the server renders the public listing,
 * and a session adds saved/applied state and the match reason.
 */
export function JobDetail() {
  const { jobId } = useParams({ strict: false }) as { jobId: string };
  const search = useSearch({ strict: false });
  const from = ("from" in search ? search.from : undefined) as JobOrigin | undefined;
  const navigate = useNavigate();
  const queryClient = useQueryClient();
  const access = useSessionAccess();
  const promote = usePromoteVisitor();

  const publicJob = usePublicJob(jobId);
  const personal = useJob(jobId, access.personal);
  const seed = useMemo(() => cachedJob(queryClient, jobId), [queryClient, jobId]);
  const job: DetailJob | undefined = personal.data ?? publicJob.data ?? seed;

  const markViewed = useMarkViewed();
  const track = useTrack();
  useEffect(() => {
    if (!access.personal) return;
    markViewed(jobId);
    track("job_opened", { type: "job", id: jobId });
  }, [access.personal, jobId, markViewed, track]);

  if (!job) {
    // Not in the public catalog: a signed-in person's own copy may still
    // exist. The server and visitors get the 404 view straight away.
    if (access.personal && personal.isPending) return <PageLoading label="Loading job" />;
    if (publicJob.data === null) return <JobNotFoundPage />;
    if (publicJob.isError) {
      return <PageFailure level={1} title="This job didn't load" onRetry={() => void publicJob.refetch()} retrying={publicJob.isFetching} />;
    }
    return <PageLoading label="Loading job" />;
  }
  return <JobView job={job} from={from} full={Boolean(personal.data ?? publicJob.data)}
    pendingDescription={Boolean(personal.data?.content_pending && !personal.data.description && personal.isFetching)}
    onRetryDescription={() => void (access.personal ? personal.refetch() : publicJob.refetch())}
    leave={() => {
      const root = jobRoot(search);
      void navigate(root === "/" ? { to: "/", search: rememberedFeedSearch(), replace: true } : { to: root, replace: true });
    }}
    navigateTo={(id) => void navigate({ to: "/jobs/$jobId", params: { jobId: id }, search: from ? { from } : {}, resetScroll: false })}
    access={access} promote={promote} />;
}

interface JobViewProps {
  job: DetailJob;
  from?: JobOrigin;
  /** False while only a list row's summary is known. */
  full: boolean;
  pendingDescription: boolean;
  onRetryDescription: () => void;
  leave: () => void;
  navigateTo: (id: string) => void;
  access: ReturnType<typeof useSessionAccess>;
  promote: () => void;
}

function JobView({ job, from, full, pendingDescription, onRetryDescription, leave, navigateTo, access, promote }: JobViewProps) {
  const navigate = useNavigate();
  const save = useSaveJob();
  const unsave = useUnsaveJob();
  const markApplied = useMarkApplied();
  const unmarkApplied = useUnmarkApplied();
  const hideJob = useHideJob();
  const hideCompany = useHideCompany();
  const block = useBlockJob();
  const [reporting, setReporting] = useState(false);
  const [confirmBlock, setConfirmBlock] = useState(false);
  const { previous, next } = useNeighbours(job.id);
  const track = useTrack();

  // j/k step through the list beside the job, as in mail and feed readers.
  useEffect(() => {
    const onKey = (event: KeyboardEvent) => {
      if (event.defaultPrevented || event.metaKey || event.ctrlKey || event.altKey) return;
      const target = event.target as HTMLElement | null;
      if (target?.closest("input, textarea, select, [contenteditable], [role=menu], [role=dialog]")) return;
      const id = event.key === "j" ? next : event.key === "k" ? previous : undefined;
      if (!id) return;
      event.preventDefault();
      navigateTo(id);
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [next, previous, navigateTo]);

  const salary = normalizeSalaryText(job.salary?.trim() ? job.salary : null);
  const location = formatJobLocation(job.location);
  const original = jobOriginalTimingLabel(job);
  const facts = quickFacts(job, salary);
  const blocks = useMemo(() => parseJobDescription(job.description, { title: job.title, companyName: job.company_name }),
    [job.description, job.title, job.company_name]);
  const saved = Boolean(job.saved);
  const applied = Boolean(job.applied);
  const closed = Boolean(job.closed_at);
  const asJob = job as Job;

  const toggleSave = () => (saved ? unsave : save).mutate(job.id, {
    onSuccess: () => { if (!saved) promote(); },
    onError: () => toast.error("Couldn't update your saved jobs. Try again."),
  });
  const setApplied = (value: boolean) => (value ? markApplied : unmarkApplied).mutate(asJob, {
    onSuccess: () => {
      promote();
      toast.success(value ? "Added to applied jobs" : "Removed from applied jobs");
    },
    onError: () => toast.error("Couldn't update this job. Try again."),
  });
  const notInterested = () => {
    hideJob(job.id).then((hidden) => {
      promote();
      leave();
      toast.show({ message: "Job hidden", duration: UNDO_TOAST_DURATION, action: { label: "Undo", run: () => hidden.undo().catch(() => { toast.error("Couldn't bring that job back."); }) } });
    }, () => toast.error("Couldn't hide this job. Try again."));
  };
  const hideTheCompany = () => {
    if (!job.company_id) return;
    hideCompany(job.company_id).then((hidden) => {
      leave();
      toast.show({ message: `${job.company_name} hidden`, duration: UNDO_TOAST_DURATION, action: { label: "Undo", run: () => hidden.undo().catch(() => { toast.error("Couldn't bring that company back."); }) } });
    }, () => toast.error("Couldn't hide this company. Try again."));
  };

  return <article className={styles.root} aria-labelledby="job-title">
    {(previous || next) && <div className={styles.stepper} role="group" aria-label="Jobs in the list">
      <IconButton icon={CaretUp} label="Previous job (K)" tooltip size="sm" disabled={!previous} onClick={() => previous && navigateTo(previous)} />
      <IconButton icon={CaretDown} label="Next job (J)" tooltip size="sm" disabled={!next} onClick={() => next && navigateTo(next)} />
    </div>}

    <header className={styles.identity}>
      <CompanyLogo name={job.company_name} domain={job.company_domain} size={44} />
      <div className={styles.heading}>
        <div className={styles.companyLine}>
          <Text as="span" size="sm" weight="medium" tone="ink-2" truncate>
            {job.company_name} · <span suppressHydrationWarning>{jobTimingLabel(job)}</span>
          </Text>
          {closed && <Badge>Closed</Badge>}
        </div>
        <Heading level={1} variant="display-md" id="job-title">{job.title}</Heading>
      </div>
    </header>

    <ul className={styles.meta}>
      {location && <li><MapPin size={15} aria-hidden /><span>{location}</span></li>}
      {salary && <li><Money size={15} aria-hidden /><span>{salary}</span></li>}
      {original && <li><ClockCounterClockwise size={15} aria-hidden /><span suppressHydrationWarning>{original}</span></li>}
    </ul>

    {facts.length > 0 && <section className={styles.facts} aria-labelledby="quick-facts">
      <h2 id="quick-facts">Quick facts</h2>
      <ul>{facts.map((fact) => <li key={fact}>{fact}</li>)}</ul>
    </section>}

    <section className={styles.about} aria-labelledby="about-role" aria-busy={pendingDescription || !full || undefined}>
      <Heading level={2} variant="section" id="about-role">About the role</Heading>
      {!full ? <div className={styles.descriptionSkeleton}>
        <Skeleton width="92%" /><Skeleton width="86%" /><Skeleton width="64%" />
      </div>
        : pendingDescription ? <Text tone="ink-2">Pulling the full posting now. This usually lands in a second or two.</Text>
        : blocks.length > 0 ? <Description blocks={blocks} />
        : <div className={styles.missing}>
          <Text tone="ink-2">We couldn’t pull the full job description yet. The original posting may still have it.</Text>
          <Button variant="secondary" size="compact" icon={ArrowCounterClockwise} onClick={onRetryDescription}>Try again</Button>
        </div>}
      {full && job.url && <a className={styles.original} href={job.url} target="_blank" rel="noopener noreferrer">
        Read the original posting <ArrowSquareOut size={13} aria-hidden />
      </a>}
    </section>

    <div className={styles.actionBar}>
      {(closed || !job.url) && !applied && <p className={styles.actionStatus} id="application-status">
        {closed ? "This listing is closed." : "Application link unavailable."}
        {access.canAct && <button type="button" className={styles.textButton} onClick={() => setReporting(true)}>Report listing</button>}
      </p>}
      <div className={styles.actions}>
        {applied
          ? <Button variant="secondary" icon={CheckCircle} disabled>Applied</Button>
          : <Button variant="primary" icon={ArrowSquareOut} disabled={closed || !job.url}
            aria-describedby={closed || !job.url ? "application-status" : undefined}
            onClick={() => {
              if (access.personal) track("apply_clicked", { type: "job", id: job.id });
              openApplication({ id: job.id, title: job.title, company_name: job.company_name, url: job.url });
            }}>
            {closed ? "Listing closed" : job.url ? "Apply" : "Link unavailable"}
          </Button>}
        {access.canAct && <Button variant="secondary" icon={saved ? SavedBookmark : BookmarkSimple} aria-pressed={saved} onClick={toggleSave}
          aria-label={saved ? "Remove from saved jobs" : "Save job"}>
          {saved ? "Saved" : "Save"}
        </Button>}
        <Menu label="More job actions" trigger={{ icon: DotsThree, label: "More job actions" }}>
          {access.canAct && (applied
            ? <MenuItem icon={ArrowCounterClockwise} onSelect={() => setApplied(false)}>I didn't apply</MenuItem>
            : <MenuItem icon={CheckCircle} onSelect={() => setApplied(true)}>I applied</MenuItem>)}
          {access.canAct && !applied && <MenuItem icon={ThumbsDown} onSelect={notInterested}>Not interested</MenuItem>}
          {access.personal && <MenuItem icon={Sparkle} onSelect={() => void navigate({ to: "/tailor/$jobId", params: { jobId: job.id }, search: from ? { from } : {} })}>Tailor resume</MenuItem>}
          <MenuItem icon={ShareNetwork} onSelect={() => void share(job)}>Share</MenuItem>
          {access.personal && job.company_id && <MenuItem icon={EyeSlash} onSelect={hideTheCompany}>Hide {job.company_name}</MenuItem>}
          {access.canAct && <MenuItem icon={Flag} onSelect={() => setReporting(true)}>Report listing</MenuItem>}
          {access.admin && <>
            <MenuSeparator />
            <MenuItem icon={Prohibit} tone="danger" onSelect={() => setConfirmBlock(true)}>Block for everyone</MenuItem>
          </>}
        </Menu>
      </div>
    </div>

    <ReportDialog jobId={job.id} open={reporting} onOpenChange={setReporting} onSent={promote} />
    <AlertDialog open={confirmBlock} onOpenChange={setConfirmBlock} title="Block this job?"
      description={`This permanently removes ${job.title} at ${job.company_name} for everyone.`}
      confirmLabel="Block job" tone="danger" pending={block.isPending}
      onConfirm={() => block.mutate(job.id, {
        onSuccess: () => { setConfirmBlock(false); leave(); toast.success("Job blocked for everyone"); },
        onError: () => toast.error("Couldn't block this job. Try again."),
      })} />
  </article>;
}
