// packages/client/src/components/OutreachSheet.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { api, ApiError, type OutreachMessage, type OutreachThread } from "@pinkslip/core/api";
  import { errorMessage } from "@pinkslip/core/utils";
  import { nextOutreachMessage, outreachMailtoUrl } from "../../../../shared/outreach";
  import { feedback } from "../lib/feedback.svelte";
  import Modal from "./Modal.svelte";
  import Spinner from "./Spinner.svelte";
  import EnvelopeSimple from "phosphor-svelte/lib/EnvelopeSimple";
  import Copy from "phosphor-svelte/lib/Copy";
  import CheckCircle from "phosphor-svelte/lib/CheckCircle";

  let {
    jobId,
    companyName,
    threadId = null,
    onclose,
  }: {
    jobId: string;
    companyName: string;
    threadId?: string | null;
    onclose: () => void;
  } = $props();

  const STEP_LABELS = ["First email", "Follow-up", "Last follow-up"] as const;

  let thread = $state<OutreachThread | null>(null);
  let loading = $state(true);
  let loadError: string | null = $state(null);
  let busy = $state(false);
  let opened = $state(false);
  let subject = $state("");
  let body = $state("");

  let next = $derived(thread ? nextOutreachMessage(thread) : null);
  let dirty = $derived(Boolean(next && (subject !== next.subject || body !== next.body)));
  let notDueYet = $derived(Boolean(next?.due_at && Date.parse(next.due_at) > Date.now()));

  function adopt(nextThread: OutreachThread) {
    const previousId = next?.id;
    thread = nextThread;
    const message = nextOutreachMessage(nextThread);
    if (message && message.id !== previousId) {
      subject = message.subject;
      body = message.body;
      opened = false;
    }
  }

  async function load() {
    loading = true;
    loadError = null;
    try {
      if (threadId) {
        adopt(await api.outreach.get(threadId));
      } else {
        const { threads } = await api.outreach.list(jobId);
        adopt(threads[0] ?? await api.outreach.start(jobId));
      }
    } catch (error) {
      loadError = error instanceof ApiError && error.code === "no_contacts"
        ? `No recruiter found for ${companyName} yet.`
        : errorMessage(error);
    } finally {
      loading = false;
    }
  }

  onMount(() => {
    void load();
  });

  async function saveEdits(): Promise<boolean> {
    if (!next || !dirty) return true;
    try {
      adopt(await api.outreach.edit(next.id, { subject, body }));
      return true;
    } catch (error) {
      feedback.error(errorMessage(error));
      return false;
    }
  }

  async function openInMail() {
    if (!thread || !next || busy) return;
    busy = true;
    try {
      if (!(await saveEdits())) return;
      window.location.href = outreachMailtoUrl(thread.contact.email, { subject, body });
      opened = true;
    } finally {
      busy = false;
    }
  }

  async function copyMessage() {
    try {
      await navigator.clipboard.writeText(`${thread?.contact.email ?? ""}\n${subject}\n\n${body}`);
      feedback.success("Copied");
    } catch {
      feedback.error("Couldn’t copy. Select the text instead.");
    }
  }

  async function run(action: () => Promise<OutreachThread | void>, done?: string) {
    if (busy) return;
    busy = true;
    try {
      const result = await action();
      if (result) adopt(result);
      if (done) feedback.success(done);
    } catch (error) {
      feedback.error(errorMessage(error));
    } finally {
      busy = false;
    }
  }

  function markSent() {
    if (!next) return;
    const messageId = next.id;
    const timeZone = Intl.DateTimeFormat().resolvedOptions().timeZone;
    void run(async () => {
      if (!(await saveEdits())) return;
      return api.outreach.markSent(messageId, timeZone);
    });
  }

  function discard() {
    if (!thread) return;
    const id = thread.id;
    void run(async () => {
      await api.outreach.discard(id);
      onclose();
    });
  }

  function formatWhen(value: string): string {
    return new Date(value).toLocaleString(undefined, {
      weekday: "short",
      month: "short",
      day: "numeric",
      hour: "numeric",
      minute: "2-digit",
    });
  }

  function stepState(message: OutreachMessage): string {
    if (message.status === "sent" && message.sent_at) return `Sent ${formatWhen(message.sent_at)}`;
    if (message.status === "scheduled" && message.due_at) return `Due ${formatWhen(message.due_at)}`;
    if (message.status === "skipped") return "Skipped";
    return "";
  }

  const closedLabel: Record<string, string> = {
    replied: "They replied",
    stopped: "Stopped",
    finished: "All sent",
  };
</script>

<Modal
  title={`Email ${companyName}`}
  subtitle={thread ? `To ${thread.contact.name || thread.contact.email}` : ""}
  maxWidth={520}
  busy={busy}
  onclose={() => { void saveEdits(); onclose(); }}
>
  {#if loading}
    <div class="page-loading" aria-busy="true"><Spinner size={22} label="Loading email" /></div>
  {:else if loadError}
    <div class="stack-sm">
      <p class="alert alert-error" role="alert">{loadError}</p>
      <button class="btn-secondary full-width" onclick={() => void load()}>Try again</button>
    </div>
  {:else if thread}
    <div class="form-stack">
      {#if thread.contact.test}
        <p class="alert alert-warn">Test recipient: {thread.contact.email}</p>
      {/if}

      <ol class="outreach-steps" aria-label="Emails">
        {#each thread.messages as message (message.id)}
          <li class:current={message.id === next?.id} class:done={message.status === "sent"}>
            {#if message.status === "sent"}
              <CheckCircle size={16} weight="fill" aria-hidden="true" />
            {:else}
              <span class="step-dot" aria-hidden="true"></span>
            {/if}
            <span class="step-label">{STEP_LABELS[message.step]}</span>
            <span class="step-state">{stepState(message)}</span>
          </li>
        {/each}
      </ol>

      {#if next}
        <input
          class="input-field"
          aria-label="Subject"
          bind:value={subject}
          onblur={() => void saveEdits()}
          disabled={busy}
        />
        <textarea
          class="input-field textarea-field outreach-body"
          aria-label="Message"
          rows="10"
          bind:value={body}
          onblur={() => void saveEdits()}
          disabled={busy}
        ></textarea>

        <div class="action-row">
          <button class="icon-btn icon-btn-surface" aria-label="Copy email" onclick={copyMessage} disabled={busy}>
            <Copy size={18} aria-hidden="true" />
          </button>
          {#if opened}
            <button class="btn-secondary" onclick={openInMail} disabled={busy}>Open again</button>
            <button class="btn-primary btn-accent flex-fill" onclick={markSent} disabled={busy}>
              {#if busy}<Spinner />{:else}<CheckCircle size={18} weight="bold" aria-hidden="true" />{/if}
              I sent it
            </button>
          {:else}
            <button class="btn-primary btn-accent flex-fill" onclick={openInMail} disabled={busy}>
              {#if busy}<Spinner />{:else}<EnvelopeSimple size={18} weight="bold" aria-hidden="true" />{/if}
              {notDueYet ? "Send early in Mail" : "Open in Mail"}
            </button>
          {/if}
        </div>

        <div class="button-cluster outreach-secondary">
          {#if thread.status === "draft"}
            <button class="text-button" onclick={discard} disabled={busy}>Discard</button>
          {:else}
            <button class="text-button" onclick={() => void run(() => api.outreach.markReplied(thread!.id), "Follow-ups stopped")} disabled={busy}>
              They replied
            </button>
            <button class="text-button" onclick={() => void run(() => api.outreach.stop(thread!.id), "Follow-ups stopped")} disabled={busy}>
              Stop follow-ups
            </button>
          {/if}
        </div>
      {:else}
        <p class="outreach-closed">{closedLabel[thread.status] ?? ""}</p>
      {/if}
    </div>
  {/if}
</Modal>

<style>
  .outreach-steps {
    display: grid;
    gap: var(--space-2);
    margin: 0;
    padding: 0;
    list-style: none;
  }

  .outreach-steps li {
    display: flex;
    align-items: center;
    gap: var(--space-2);
    color: var(--color-ink-3);
    font-size: var(--fs-sm);
  }

  .outreach-steps li.current {
    color: var(--color-ink);
  }

  .outreach-steps li.done {
    color: var(--color-ink-2);
  }

  .outreach-steps li.done :global(svg) {
    color: var(--color-good);
  }

  .step-dot {
    width: 16px;
    height: 16px;
    flex: none;
    border: 1.5px solid var(--color-line);
    border-radius: var(--radius-full);
  }

  .outreach-steps li.current .step-dot {
    border-color: var(--color-accent);
  }

  .step-label {
    font-weight: 500;
  }

  .step-state {
    margin-left: auto;
    font-variant-numeric: tabular-nums;
  }

  .outreach-body {
    min-height: 220px;
    line-height: 1.45;
  }

  .outreach-secondary {
    justify-content: center;
  }

  .outreach-closed {
    margin: 0;
    color: var(--color-ink-2);
    text-align: center;
  }
</style>

// apps/native/src/features/apply/OutreachSheet.tsx
import { ApiError } from "@pinkslip/core/api";
import { nextOutreachMessage, outreachMailtoUrl, type OutreachMessage, type OutreachThread } from "@pinkslip/domain/outreach";
import { useOutreachAction, useOutreachThread } from "@pinkslip/data";
import * as Clipboard from "expo-clipboard";
import { CheckCircle, Copy, EnvelopeSimple, WarningCircle } from "phosphor-react-native";
import { useEffect, useRef, useState } from "react";
import { Linking, View } from "react-native";
import { StyleSheet, useUnistyles } from "react-native-unistyles";
import { Button, EmptyState, IconButton, Input, Sheet, Spinner, Stack, Text, Textarea, toast } from "../../kit";
import { haptics } from "../../platform/haptics";

const STEP_LABELS = ["First email", "Follow-up", "Last follow-up"] as const;
const CLOSED: Record<string, string> = { replied: "They replied", stopped: "Follow-ups stopped", finished: "All sent" };
const when = (iso: string) => new Date(iso).toLocaleString(undefined, { weekday: "short", month: "short", day: "numeric", hour: "numeric", minute: "2-digit" });

function stepState(message: OutreachMessage): string {
  if (message.status === "sent" && message.sent_at) return `Sent ${when(message.sent_at)}`;
  if (message.status === "scheduled" && message.due_at) return `Due ${when(message.due_at)}`;
  if (message.status === "skipped") return "Skipped";
  return "";
}

/** The recruiter email (`OutreachSheet.svelte`): the draft and two
 * follow-ups. You send from Mail, then confirm "I sent it", which schedules
 * the next one. A reminder opens this from the job with `?outreach=`. */
export function OutreachSheet({ jobId, companyName, threadId, open, onOpenChange }: {
  jobId: string;
  companyName: string;
  threadId: string | null;
  open: boolean;
  onOpenChange: (open: boolean) => void;
}) {
  const thread = useOutreachThread(jobId, threadId, open);
  const noContact = thread.error instanceof ApiError && thread.error.code === "no_contacts";
  return <Sheet open={open} onOpenChange={onOpenChange} title={`Email ${companyName}`}
    subtitle={thread.data ? `To ${thread.data.contact.name || thread.data.contact.email}` : undefined}>
    {thread.isPending ? <View style={styles.loading}><Spinner label="Loading email" /></View>
      : thread.isError ? <EmptyState icon={WarningCircle} title={noContact ? `No recruiter found for ${companyName} yet` : "Couldn't load this email"}
        actions={noContact ? undefined : <Button pending={thread.isFetching} onPress={() => void thread.refetch()}>Try again</Button>} />
      : <Composer jobId={jobId} threadId={threadId} thread={thread.data} onClose={() => onOpenChange(false)} />}
  </Sheet>;
}

function Composer({ jobId, threadId, thread, onClose }: { jobId: string; threadId: string | null; thread: OutreachThread; onClose: () => void }) {
  const { theme } = useUnistyles();
  const action = useOutreachAction(jobId, threadId);
  const next = nextOutreachMessage(thread);
  const [subject, setSubject] = useState(next?.subject ?? "");
  const [body, setBody] = useState(next?.body ?? "");
  const [opened, setOpened] = useState(false);
  const shown = useRef(next?.id);

  useEffect(() => {
    if (next && next.id !== shown.current) {
      shown.current = next.id;
      setSubject(next.subject);
      setBody(next.body);
      setOpened(false);
    }
  }, [next]);

  const failed = () => toast.error("Couldn't update this email. Try again.");
  const dirty = Boolean(next && (subject !== next.subject || body !== next.body));
  const saveEdits = async () => {
    if (!next || !dirty) return true;
    try { await action.mutateAsync({ kind: "edit", messageId: next.id, subject, body }); return true; } catch { failed(); return false; }
  };
  const openInMail = async () => {
    if (!(await saveEdits())) return;
    await Linking.openURL(outreachMailtoUrl(thread.contact.email, { subject, body })).catch(() => toast.error("Couldn't open Mail. Copy the email instead."));
    setOpened(true);
  };
  const copy = async () => {
    await Clipboard.setStringAsync(`${thread.contact.email}\n${subject}\n\n${body}`);
    haptics.tap();
    toast.success("Copied");
  };
  const markSent = async () => {
    if (!next || !(await saveEdits())) return;
    action.mutate({ kind: "sent", messageId: next.id, timeZone: Intl.DateTimeFormat().resolvedOptions().timeZone }, { onSuccess: () => haptics.success(), onError: failed });
  };
  const busy = action.isPending;
  const notDueYet = Boolean(next?.due_at && Date.parse(next.due_at) > Date.now());

  return <Stack gap="4">
    {thread.contact.test && <Text size="sm" tone="warn">Test recipient: {thread.contact.email}</Text>}
    <Stack gap="2">
      {thread.messages.map((message) => <View key={message.id} style={styles.step}>
        {message.status === "sent" ? <CheckCircle size={16} weight="fill" color={theme.colors.good} /> : <View style={styles.dot} />}
        <Text size="sm" weight={message.id === next?.id ? "medium" : "regular"} tone={message.id === next?.id ? "ink" : "ink-3"}>{STEP_LABELS[message.step]}</Text>
        <Text size="sm" tone="ink-3">{stepState(message)}</Text>
      </View>)}
    </Stack>
    {next ? <>
      <Input accessibilityLabel="Subject" value={subject} editable={!busy} onChangeText={setSubject} onBlur={() => void saveEdits()} />
      <Textarea accessibilityLabel="Message" value={body} editable={!busy} onChangeText={setBody} onBlur={() => void saveEdits()} style={{ minHeight: 220 }} />
      <View style={styles.actions}>
        <IconButton icon={Copy} label="Copy email" disabled={busy} onPress={() => void copy()} />
        {opened && <Button disabled={busy} onPress={() => void openInMail()}>Open again</Button>}
        <View style={styles.primary}>
          {opened ? <Button variant="primary" icon={CheckCircle} fullWidth pending={busy} onPress={() => void markSent()}>I sent it</Button>
            : <Button variant="primary" icon={EnvelopeSimple} fullWidth pending={busy} onPress={() => void openInMail()}>{notDueYet ? "Send early in Mail" : "Open in Mail"}</Button>}
        </View>
      </View>
      <View style={styles.secondary}>
        {thread.status === "draft"
          ? <Text tone="accent" onPress={busy ? undefined : () => action.mutate({ kind: "discard", threadId: thread.id }, { onSuccess: onClose, onError: failed })}>Discard</Text>
          : <>
            <Text tone="accent" onPress={busy ? undefined : () => action.mutate({ kind: "replied", threadId: thread.id }, { onSuccess: () => toast.success("Follow-ups stopped"), onError: failed })}>They replied</Text>
            <Text tone="accent" onPress={busy ? undefined : () => action.mutate({ kind: "stop", threadId: thread.id }, { onSuccess: () => toast.success("Follow-ups stopped"), onError: failed })}>Stop follow-ups</Text>
          </>}
      </View>
    </> : <Text tone="ink-2">{CLOSED[thread.status] ?? ""}</Text>}
  </Stack>;
}

const styles = StyleSheet.create((theme) => ({
  loading: { alignItems: "center", paddingVertical: 48 },
  step: { flexDirection: "row", alignItems: "center", gap: theme.space["2"] },
  dot: { width: 10, height: 10, marginHorizontal: 3, borderRadius: 5, borderWidth: 1.5, borderColor: theme.colors["ink-3"] },
  actions: { flexDirection: "row", alignItems: "center", gap: theme.space["2"] },
  primary: { flex: 1 },
  secondary: { flexDirection: "row", justifyContent: "center", gap: theme.space["5"] },
}));
