// apps/native/src/features/onboarding/Onboarding.tsx
import { applyImport, importSummary } from "@pinkslip/core/resume-import-apply";
import type { Profile } from "@pinkslip/core/profile-fields";
import { normalizeResumeProfile } from "@pinkslip/domain/resume-profile";
import { normalizeSearchProfile, ONBOARDING_VERSION } from "@pinkslip/domain/search-profile";
import { useApi, usePreferences, useSaveResume, useUpdatePreferences, useUpdatePushSettings } from "@pinkslip/data";
import { router } from "expo-router";
import { BellRinging, CaretLeft, Check, UploadSimple, WarningCircle } from "phosphor-react-native";
import { useEffect, useRef, useState } from "react";
import { ScrollView, View } from "react-native";
import Animated, { FadeIn } from "react-native-reanimated";
import { StyleSheet, useUnistyles } from "react-native-unistyles";
import { Button, EmptyState, Heading, IconButton, Spinner, Stack, Text, toast } from "../../kit";
import { haptics } from "../../platform/haptics";
import { devicePushStatus, enableDevicePush, type DevicePushStatus } from "../../platform/push";
import { MetroField, RoleField, StageField, WorkFields } from "../preferences/ProfileFields";
import { pickAndImportResume, ResumeImportFailure } from "../resume/import";

const STEPS = 4;

/** Onboarding (port plan 4.7), full screen: what you're looking for, where,
 * a skippable resume, then alerts. Keeps the version/completion stamp and
 * the started/completed events. Never blocks browsing ("Not now"). */
export function Onboarding() {
  const preferences = usePreferences();
  if (preferences.isPending) return <View style={styles.center}><Spinner label="Loading" /></View>;
  if (preferences.isError) {
    return <View style={styles.center}><EmptyState icon={WarningCircle} title="Setup didn't load" actions={<Button onPress={() => void preferences.refetch()}>Try again</Button>} /></View>;
  }
  return <Steps initial={normalizeSearchProfile(preferences.data.search_profile)} />;
}

function Steps({ initial }: { initial: Profile }) {
  const { theme } = useUnistyles();
  const api = useApi();
  const save = useUpdatePreferences();
  const updatePush = useUpdatePushSettings();
  const saveResume = useSaveResume();
  const [step, setStep] = useState(1);
  const [profile, setProfile] = useState(initial);
  const [push, setPush] = useState<DevicePushStatus | "error" | null>(null);
  const [enabling, setEnabling] = useState(false);
  const [resume, setResume] = useState<{ state: "idle" | "importing" } | { state: "done"; summary: string } | { state: "error"; message: string }>({ state: "idle" });
  const started = useRef(false);
  const scroll = useRef<ScrollView>(null);
  const change = (patch: Partial<Profile>) => setProfile((current) => ({ ...current, ...patch }));
  const event = (name: string, properties: Record<string, string | number | boolean> = {}) =>
    void api.interactions.event({ event_name: name, entity_type: "onboarding", properties: { onboarding_version: ONBOARDING_VERSION, ...properties } }).catch(() => undefined);

  useEffect(() => { void devicePushStatus().then((status) => { if (status === "enabled") setPush("enabled"); }); }, []);
  useEffect(() => { scroll.current?.scrollTo({ y: 0, animated: false }); }, [step]);

  const leave = () => (router.canGoBack() ? router.back() : router.replace("/"));
  const next = async () => {
    if (step === 1) {
      if (!started.current) { started.current = true; event("onboarding_started"); }
      setStep(2);
      return;
    }
    if (step === 2) {
      try {
        const saved = await save.mutateAsync({ search_profile: profile });
        setProfile(normalizeSearchProfile(saved.search_profile));
        setStep(3);
      } catch {
        toast.error("Couldn't save your search. Try again.");
      }
      return;
    }
    if (step === 3) { setStep(4); return; }
    try {
      await save.mutateAsync({ search_profile: { ...profile, notifications_enabled: push === "enabled", onboarding_version: ONBOARDING_VERSION, onboarding_completed_at: new Date().toISOString() } });
      event("onboarding_completed", { notifications_enabled: push === "enabled" });
      haptics.success();
      leave();
    } catch {
      toast.error("Couldn't finish setup. Try again.");
    }
  };

  const importFile = async () => {
    setResume({ state: "importing" });
    try {
      const imported = await pickAndImportResume(api);
      if (!imported) { setResume({ state: "idle" }); return; }
      const current = normalizeResumeProfile((await api.profile.get()).data);
      await saveResume.mutateAsync(applyImport(current, imported.profile, normalizeResumeProfile));
      setResume({ state: "done", summary: importSummary(imported.profile) || "Contact details" });
    } catch (error) {
      setResume({ state: "error", message: error instanceof ResumeImportFailure ? error.message : "Couldn't import that resume. Try again." });
    }
  };

  const turnOnAlerts = async () => {
    setEnabling(true);
    try {
      const result = await enableDevicePush(api);
      setPush(result);
      if (result === "enabled") await updatePush.mutateAsync(true);
    } catch {
      setPush("error");
    } finally {
      setEnabling(false);
    }
  };

  const titles = ["What are you looking for?", "Where can you work?", "Add your resume", "Hear about new jobs first"];
  return <View style={styles.root}>
    <View style={styles.header}>
      <View style={styles.back}>{step > 1 && <IconButton icon={CaretLeft} label="Back" onPress={() => setStep(step - 1)} />}</View>
      <View style={styles.progress} accessibilityRole="progressbar" accessibilityValue={{ min: 1, max: STEPS, now: step, text: `Step ${step} of ${STEPS}` }}>
        {Array.from({ length: STEPS }, (_, index) => <View key={index} style={[styles.segment, index < step && styles.segmentOn]} />)}
      </View>
      <View style={styles.back} />
    </View>
    <ScrollView ref={scroll} contentContainerStyle={styles.body} keyboardDismissMode="interactive">
      <Animated.View key={step} entering={FadeIn.duration(220)}>
        <Stack gap="6">
          <Heading variant="display-lg">{titles[step - 1]}</Heading>
          {step === 1 && <><StageField profile={profile} onChange={change} /><RoleField profile={profile} onChange={change} /></>}
          {step === 2 && <><WorkFields profile={profile} onChange={change} /><MetroField profile={profile} onChange={change} /></>}
          {step === 3 && <>
            <Text tone="ink-2">It fills in applications for you. You can skip this and add it later.</Text>
            {resume.state === "done" ? <View style={styles.done}><Check size={18} weight="bold" color={theme.colors.good} /><Text tone="good">Imported {resume.summary}</Text></View>
              : <Button fullWidth icon={UploadSimple} pending={resume.state === "importing"} onPress={() => void importFile()}>{resume.state === "importing" ? "Reading your resume…" : "Import from PDF"}</Button>}
            {resume.state === "error" && <Text tone="bad">{resume.message}</Text>}
          </>}
          {step === 4 && <>
            <Text tone="ink-2">We'll send an alert when a new posting fits your search.</Text>
            {push === "enabled" ? <View style={styles.done}><Check size={18} weight="bold" color={theme.colors.good} /><Text tone="good">Alerts are on for this iPhone</Text></View>
              : push === "denied" || push === "unsupported" ? <Text tone="warn">Alerts are off for Pinkslip in Settings. You can turn them on later in You.</Text>
              : <Button fullWidth icon={BellRinging} pending={enabling} onPress={() => void turnOnAlerts()}>Turn on alerts</Button>}
            {push === "error" && <Text tone="bad">Couldn't turn on alerts. Try again, or later in You.</Text>}
          </>}
        </Stack>
      </Animated.View>
    </ScrollView>
    <View style={styles.footer}>
      <Button variant="primary" fullWidth pending={save.isPending} disabled={enabling || resume.state === "importing"} onPress={() => void next()}>
        {step === STEPS ? "Show my jobs" : step === 3 && resume.state !== "done" ? "Skip for now" : "Continue"}
      </Button>
      {step === 1 && <Button fullWidth onPress={leave}>Not now</Button>}
    </View>
  </View>;
}

const styles = StyleSheet.create((theme, rt) => ({
  root: { flex: 1, backgroundColor: theme.colors.bg, paddingTop: rt.insets.top },
  center: { flex: 1, justifyContent: "center", backgroundColor: theme.colors.bg },
  header: { flexDirection: "row", alignItems: "center", paddingHorizontal: theme.space["2"], height: 56 },
  back: { width: 44 },
  progress: { flex: 1, flexDirection: "row", gap: theme.space["1"], paddingHorizontal: theme.space["2"] },
  segment: { flex: 1, height: 4, borderRadius: 2, backgroundColor: theme.colors["control-bg"] },
  segmentOn: { backgroundColor: theme.colors.accent },
  body: { padding: theme.gutter, paddingTop: theme.space["4"], paddingBottom: theme.space["10"] },
  done: { flexDirection: "row", alignItems: "center", gap: theme.space["2"] },
  footer: { gap: theme.space["2"], paddingHorizontal: theme.gutter, paddingTop: theme.space["3"], paddingBottom: rt.insets.bottom + theme.space["2"] },
}));

// packages/client/src/components/Onboarding.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { api } from "../lib/api";
  import { errorMessage } from "../lib/utils";
  import { enableNativePush, getNativePushStatus, isNativeIos } from "../lib/native-push";
  import {
    DEFAULT_SEARCH_PROFILE,
    ONBOARDING_VERSION,
    normalizeSearchProfile,
    type SearchProfile,
  } from "../../../../shared/search-profile";
  import SearchProfileFields from "./SearchProfileFields.svelte";
  import BrandMark from "./BrandMark.svelte";
  import CaretLeft from "phosphor-svelte/lib/CaretLeft";
  import Check from "phosphor-svelte/lib/Check";
  import Bell from "phosphor-svelte/lib/Bell";
  import Spinner from "./Spinner.svelte";
  import { invalidateFeedForPreferences } from "../lib/feed-store.svelte";

  let {
    initialProfile,
    onComplete,
  }: {
    initialProfile: SearchProfile;
    onComplete: (name: string) => void;
  } = $props();

  const TOTAL_STEPS = 3;

  let step = $state(1);
  let saving = $state(false);
  let enablingPush = $state(false);
  let pushStatus: "idle" | "enabled" | "denied" | "error" = $state("idle");
  let profile: SearchProfile = $state(normalizeSearchProfile(DEFAULT_SEARCH_PROFILE));
  let error: string | null = $state(null);
  let onboardingStartRecorded = false;
  let profileInitialized = false;
  let scrollEl: HTMLDivElement | null = $state(null);

  $effect(() => {
    if (profileInitialized) return;
    profile = normalizeSearchProfile(initialProfile);
    profileInitialized = true;
  });

  onMount(() => {
    let active = true;
    void getNativePushStatus()
      .then((status) => {
        if (active && status === "enabled") {
          pushStatus = "enabled";
          profile = normalizeSearchProfile({ ...profile, notifications_enabled: true });
        }
      })
      .catch(() => undefined);
    return () => { active = false; };
  });

  $effect(() => {
    step;
    if (scrollEl) scrollEl.scrollTop = 0;
  });

  async function beginOnboarding() {
    if (!onboardingStartRecorded) {
      onboardingStartRecorded = true;
      void api.interactions.event({
        event_name: "onboarding_started",
        entity_type: "onboarding",
        properties: { onboarding_version: ONBOARDING_VERSION },
      }).catch(() => undefined);
    }
    step = 2;
  }

  function goBack() {
    if (step <= 1 || saving || enablingPush) return;
    error = null;
    step -= 1;
  }

  async function saveSearchProfile() {
    if (profile.roles.length === 0 || profile.work_modes.length === 0 || saving) return;
    saving = true;
    error = null;
    try {
      const saved = await api.preferences.update({ search_profile: profile });
      profile = normalizeSearchProfile(saved.search_profile);
      step = 3;
    } catch (caught) {
      error = errorMessage(caught, "Could not save your search. Check your connection and try again.");
    } finally {
      saving = false;
    }
  }

  async function handleEnablePush() {
    if (enablingPush) return;
    enablingPush = true;
    error = null;
    try {
      const enabled = (await enableNativePush()) === "enabled";
      pushStatus = enabled ? "enabled" : "denied";
      if (enabled) {
        await api.push.updateSettings({ enabled: true, push_enabled: true });
        profile = normalizeSearchProfile({ ...profile, notifications_enabled: true });
      }
    } catch {
      pushStatus = "error";
    } finally {
      enablingPush = false;
    }
  }

  async function finish() {
    if (saving) return;
    saving = true;
    error = null;
    try {
      const saved = await api.preferences.update({
        search_profile: {
          ...profile,
          onboarding_version: ONBOARDING_VERSION,
          onboarding_completed_at: new Date().toISOString(),
        },
      });
      profile = normalizeSearchProfile(saved.search_profile);
      invalidateFeedForPreferences(profile);
      void api.interactions.event({
        event_name: "onboarding_completed",
        entity_type: "onboarding",
        properties: {
          onboarding_version: ONBOARDING_VERSION,
          notifications_enabled: profile.notifications_enabled,
        },
      }).catch(() => undefined);
      onComplete("");
    } catch (caught) {
      error = errorMessage(caught, "Could not finish setup. Check your connection and try again.");
    } finally {
      saving = false;
    }
  }
</script>

<div class="onboarding">
  <header class="onboarding-header">
    <div class="onboarding-header-row">
      <button
        type="button"
        class="onboarding-back"
        class:hidden={step === 1}
        aria-label="Back"
        tabindex={step === 1 ? -1 : 0}
        onclick={goBack}
      >
        <CaretLeft size={21} weight="bold" />
      </button>
      <div class="onboarding-brand" aria-label="pinkslip">
        <BrandMark size={28} />
        <span><strong>pink</strong>slip</span>
      </div>
      <span aria-hidden="true"></span>
    </div>
    <div class="onboarding-progress-track" aria-label={`Step ${step} of ${TOTAL_STEPS}`}>
      {#each Array.from({ length: TOTAL_STEPS }, (_, index) => index + 1) as item}
        <span class:active={item <= step}></span>
      {/each}
    </div>
  </header>

  <div bind:this={scrollEl} class="onboarding-scroll">
    <main class="onboarding-content">
      {#if step === 1}
        <section class="onboarding-step">
          <h1>Beat the crowd</h1>
          <p class="onboarding-copy">
            Choose the roles you want. We&rsquo;ll alert you the moment we see a new posting.
          </p>
          <div class="onboarding-fields">
            <SearchProfileFields bind:profile section="roles" showAdvanced={false} showHeadings={false} />
          </div>
        </section>

      {:else if step === 2}
        <section class="onboarding-step">
          <h1>Set your work preferences</h1>
          <div class="onboarding-fields onboarding-fields-after-title">
            <SearchProfileFields bind:profile section="locations" showAdvanced={false} showHeadings={false} />
          </div>
          {#if error}
            <div class="alert alert-error onboarding-alert" role="alert">{error}</div>
          {/if}
        </section>

      {:else}
        <section class="onboarding-step">
          <h1>Stay in the loop</h1>
          <p class="onboarding-copy">
            Get an alert when a new role fits your search.
          </p>

          {#if pushStatus === "enabled"}
            <div class="onboarding-status success">
              <Check size={17} weight="bold" /> Alerts are on for this device
            </div>
          {:else}
            <button
              type="button"
              class="btn-secondary full-width tall-control onboarding-alert-action"
              disabled={enablingPush}
              onclick={handleEnablePush}
            >
              {#if enablingPush}<Spinner />{:else}<Bell size={17} />{/if}
              Enable notifications
            </button>
            <p class="onboarding-footnote">Alerts can be turned on later.</p>
          {/if}

          {#if pushStatus === "denied"}
            <div class="alert alert-warn onboarding-alert">
              Permission is off. You can enable alerts later in {isNativeIos() ? "iOS Settings" : "your browser settings"}.
            </div>
          {:else if pushStatus === "error"}
            <div class="alert alert-error onboarding-alert" role="alert">
              Unable to turn on alerts. Check your connection and try again.
            </div>
          {:else if error}
            <div class="alert alert-error onboarding-alert" role="alert">{error}</div>
          {/if}

        </section>
      {/if}
    </main>
  </div>

  <footer class="onboarding-footer">
    <div class="onboarding-footer-inner">
      {#if step === 1}
        <button
          type="button"
          class="btn-primary btn-accent full-width onboarding-cta"
          disabled={profile.roles.length === 0}
          onclick={beginOnboarding}
        >Continue</button>
      {:else if step === 2}
        <button
          type="button"
          class="btn-primary btn-accent full-width onboarding-cta"
          disabled={saving || profile.work_modes.length === 0}
          onclick={saveSearchProfile}
        >
          {#if saving}<Spinner />{/if}
          Continue
        </button>
      {:else}
        <button
          type="button"
          class="btn-primary btn-accent full-width onboarding-cta"
          disabled={saving || enablingPush}
          onclick={finish}
        >
          {#if saving}<Spinner />{/if}
          Start using pinkslip
        </button>
      {/if}
    </div>
  </footer>
</div>

<style>
  .onboarding {
    position: fixed;
    inset: 0;
    z-index: var(--z-overlay);
    display: flex;
    flex-direction: column;
    padding: var(--safe-top) 0 0;
    background: var(--color-bg);
    overscroll-behavior: contain;
  }

  .onboarding-header {
    flex: none;
    padding: 6px var(--space-4) 12px;
    background: var(--color-bg);
  }

  .onboarding-header-row {
    min-height: var(--screen-nav-height);
    display: grid;
    grid-template-columns: var(--tap-min) minmax(0, 1fr) var(--tap-min);
    align-items: center;
    gap: var(--space-3);
  }

  .onboarding-back {
    width: var(--tap-min);
    height: var(--tap-min);
    padding: 0;
    display: grid;
    place-items: center;
    border: 0;
    border-radius: var(--radius-md);
    background: transparent;
    color: var(--color-ink);
    cursor: pointer;
  }

  .onboarding-back.hidden {
    visibility: hidden;
    pointer-events: none;
  }

  .onboarding-back:hover { background: var(--color-bg-sunken); }

  .onboarding-progress-track {
    width: min(100%, 400px);
    margin: 0 auto;
    display: flex;
    gap: var(--space-2);
  }

  .onboarding-progress-track span {
    height: 3px;
    flex: 1;
    border-radius: var(--radius-full);
    background: var(--color-line);
    transition: background var(--duration-fast) var(--ease-standard);
  }

  .onboarding-progress-track span.active { background: var(--color-accent); }

  .onboarding-scroll {
    min-height: 0;
    flex: 1;
    overflow-y: auto;
    display: flex;
    justify-content: center;
    padding: var(--space-6) var(--space-5);
  }

  .onboarding-content {
    width: 100%;
    max-width: 400px;
    margin-block: 0;
  }

  .onboarding-step {
    animation: onboarding-enter var(--duration-standard) var(--ease-standard) both;
  }

  .onboarding-brand {
    display: flex;
    align-items: center;
    justify-self: center;
    gap: 8px;
    color: var(--color-ink);
  }

  .onboarding-brand span {
    font-size: var(--fs-lg);
    font-weight: 600;
    letter-spacing: -0.025em;
  }

  .onboarding-brand strong {
    color: var(--color-accent);
    font-weight: 600;
  }

  .onboarding h1 {
    max-width: 18ch;
    margin: 0 0 var(--space-3);
    color: var(--color-ink);
    font-family: var(--font-pixel);
    font-size: var(--fs-4xl);
    font-weight: 400;
    letter-spacing: 0;
    line-height: 1.15;
  }

  .onboarding-copy {
    max-width: 42ch;
    margin: 0 0 var(--space-6);
    color: var(--color-ink-2);
    font-size: var(--fs-md);
    line-height: 1.5;
  }

  .onboarding-fields { margin-bottom: 0; }
  .onboarding-fields-after-title { margin-top: var(--space-6); }
  .onboarding-alert { margin: var(--space-3) 0 0; }
  .onboarding-footer {
    flex: none;
    padding: 12px var(--space-5) calc(12px + var(--safe-bottom));
    background: color-mix(in oklch, var(--color-bg) 94%, transparent);
    box-shadow: 0 -1px 0 var(--color-line);
    backdrop-filter: blur(14px);
    -webkit-backdrop-filter: blur(14px);
  }

  .onboarding-footer-inner {
    width: 100%;
    max-width: 400px;
    margin: 0 auto;
  }

  .onboarding-cta { margin: 0; }

  .onboarding-alert-action { margin-top: var(--space-2); }

  .onboarding-status {
    min-height: 48px;
    padding: 0 var(--space-3);
    display: flex;
    align-items: center;
    gap: var(--space-2);
    border: 1px solid var(--color-message-border);
    border-radius: var(--radius-md);
    font-size: var(--fs-sm);
    font-weight: 500;
  }

  .onboarding-status.success {
    background: var(--color-good-soft);
    color: var(--color-good);
  }

  .onboarding-footnote {
    margin: 8px 0 0;
    color: var(--color-ink-4);
    font-size: var(--fs-xs);
    line-height: 1.4;
    text-align: center;
  }

  @keyframes onboarding-enter {
    from { opacity: 0; transform: translateY(4px); }
    to { opacity: 1; transform: translateY(0); }
  }

  @media (min-width: 720px) {
    .onboarding-scroll { padding-block: var(--space-8); }
  }
</style>
